enum AppraisalsEnum {
	BUILDING_WITH_LAND = 'building_with_land',
	LAND_ONLY = 'land_only',
	APPRAISAL_ID = 'appraisal_id',
	TYPE_MY_OWN = 'Type My Own',
	SF = 'SF',
	UNIT = 'Unit',
	BED = 'Bed',
	MULTI_FAMILY = 'multi_family',
	SALE = 'sale',
	LEASE = 'lease',
	TOPOGRAPHY = 'topography',
	LOT_SHAPE = 'lot_shape',
	UTILITIES_SELECT = 'utilities_select',
	FRONTAGE = 'frontage',
	CONDITION = 'condition',
	PARKING = 'parking',
	LAND_TYPE = 'land_type',
	DATE_SOLD = 'date_sold',
	TYPE = 'type',
	COMP_TYPE = 'comp_type',
	COMPARISON_BASIS = 'comparison_basis',
	BASEMENT = 'basement',
	EXTERIOR = 'exterior',
	ROOF = 'roof',
	ELECTRICAL = 'electrical',
	PLUMBING = 'plumbing',
	HEATING_COOLING = 'heating_cooling',
	WINDOWS = 'windows',
	BEDROOMS = 'bedrooms',
	BATHROOMS = 'bathrooms',
	GARAGE = 'garage',
	FENCING = 'fencing',
	FIREPLACE = 'fireplace',
	NON_SALE = 'non_sale',
	YES = 'yes',
	NO = 'no',
	PRICE_SF = '$/SF',
	PRICE_ACRE = '$/Acre',
	ACRE = 'ACRE',
	AC = 'AC',
	MOST_LIKELY_OWNER_USER = 'most_likely_owner_user',
	MAIN_STRUCTURE_BASE = 'main_structure_base',
	FOUNDATION = 'foundation',
	ADA_COMPLIANCE = 'ada_compliance',
	PROPERTY_CLASS = 'property_class',
	PROPERTY_RIGHTS = 'property_rights',
	BUSINESS_NAME = 'business_name',
	COST = 'cost',
	INCOME = 'income',
	ROADMAP = 'roadmap',
	COST_AREA_MAP = 'save-cost-area-map',
	SALE_AREA_MAP = 'save-sale-area-map',
	LEASE_AREA_MAP = 'save-lease-area-map',
	SQ_FT = 'sq_ft',
	SQUARE_FEET = 'square_feet',
	SF_SOURCE = 'sf_source',
	ORDER_BY_COLUMN = 'order',
	ID = 'id',
	NA = 'N/A',
	PERCENT = '%',
	LAND_ONLY_TYPE = 'Land Only',
	BUILDING_SIZE = 'building_size',
	CALCULATE_LAND = 43560,
	STREET_ADDRESS = 'street_address',
	PENDING = 'Pending',
	LAND = 'land',
	INCOME_COMPARISON = 'income_comparison',
	RENT_ROLL = 'rent_roll',
}

export enum ImagesEnum {
	HORIZONTAL = 'Horizontal',
	VERTICAL = 'Vertical',
}

export enum ImagesTitleEnum {
	SUB_PROPERTY = 'Sub. Property',
	SUB_PROPERTY_2 = 'Sub. Property 2',
	SUB_PROPERTY_3 = 'Sub. Property 3',
	SUB_PROPERTY_4 = 'Sub. Property 4',
	SUB_PROPERTY_5 = 'Sub. Property 5',
	SUB_PROPERTY_6 = 'Sub. Property 6',
	SUB_PROPERTY_7 = 'Sub. Property 7',
	SUB_PROPERTY_8 = 'Sub. Property 8',
	ADDITIONAL_IMAGE = 'Additional image',
	PHOTO_PAGE = 'Photo page',
}

export enum ImagesPageEnum {
	COVER_PHOTO = '1 - Cover Photo',
	TABLE_OF_CONTENTS = '2 - Table of Contents',
	EXECUTIVE_SUMMARY = '3 - Executive Summary',
	PROPERTY_SUMMARY = '4 - Property Summary',
	EXTRA_IMAGE = 'Extra image uploaded by user',
	COVER = 'cover',
	PHOTO = 'photo',
}

export enum AreaInfoEnum {
	CITY_INFO = 'city_info',
	COUNTY_INFO = 'county_info',
	PROPERTY_SUMMARY_SALES_ARROW = 'property_summary_sales_arrow',
	PROPERTY_SUMMARY_VACANCY_ARROW = 'property_summary_vacancy_arrow',
	PROPERTY_SUMMARY_NET_ABSORPTION_ARROW = 'property_summary_net_absorption_arrow',
	PROPERTY_SUMMARY_CONSTRUCTION_ARROW = 'property_summary_construction_arrow',
	PROPERTY_SUMMARY_LEASE_RATES_ARROW = 'property_summary_lease_rates_arrow',
}

export enum IncomeApproachEnum {
	APPRAISAL_INCOME_APPROACH_ID = 'appraisal_income_approach_id',
	RENT_SQ_FT = 'rent_sq_ft',
	RENT = 'rent_',
	TOTAL_RENT = 'total_rent',
	HIGH_CAP_RATE = 'high_capitalization_rate',
	TOTAL_OE_PER_SQUARE_FEET = 'total_oe_per_square_feet',
	TOTAL_PER = 'total_per',
	TOTAL = 'total',
	TOTAL_OE_PER = 'total_oe_per',
	CAPITALIZATION_RATE = 'capitalization_rate',
	SQ_FT_CAP_RATE = 'sq_ft_capitalization_rate',
	INDICATED_RANGE = 'indicated_range',
}

export enum ReportTemplateEnum {
	SUBSECTION = 'subsection',
	APPROACH = 'approach',
	MAP = 'map',
	AERIAL_MAP = 'aerial_map',
	IMAGE = 'image',
	TEXT_BLOCK = 'text_block',
	RED = 'red',
	BLUE = 'blue',
	GREEN = 'green',
	YELLOW = 'yellow',
	ORANGE = 'orange',
	PURPLE = 'purple',
	PINK = 'pink',
	MAP_BOUNDARY = 'map_boundary',
	PHOTO_PAGES = 'photo_pages',
	BUILDING_SIZE = 'Building Size',
}

export enum SaleComparativeAttribute {
	CITY_STATE = 'city_state',
	SALE_PRICE = 'sale_price',
	LAND_SIZE_SF = 'land_size_sf',
	LAND_SIZE_AC = 'land_size_acre',
	ZONING_TYPE = 'zoning_type',
	ZONE = 'zone',
	YEAR_BUILT_REMODELED = 'year_built_year_remodeled',
	QUALITY_CONDITION = 'quality_condition',
	UNIT_MIX = 'unit_mix',
	PRICE_PER_SF = 'price_per_sf',
	PRICE_PER_UNIT = 'price_per_unit',
	PRICE_PER_ACRE = 'price_per_acre',
	CAP_RATE = 'cap_rate',
	GRANTOR = 'grantor',
	GRANTEE = 'grantee',
	PRICE_PER_SF_LAND = 'price_per_sf_land',
	UNIT_SIZE_SF = 'unit_size_sq_ft',
	EFFECTIVE_AGE = 'effective_age',
	CITY_COUNTY = 'city_county',
	NO_OF_UNIT = 'unit',
}
export enum GlobalCodeEnums {
	ZONE = 'zone',
	STATES = 'states',
	LAND_TYPE = 'land_type',
	CONDITION = 'condition',
	SUB_ZONE = 'sub_zone',
}

export default AppraisalsEnum;
