export interface AppraisalGetOverviewDataType {
  data: {
    data: {
      account_id: number;
      ada_compliance: null | string;
      additional_feature: null | string;
      aerial_map_type: string;
      aerial_map_zoom: null;
      analysis_type: string;
      country: string;
      appraisal_approaches: [
        {
          id: number;
          name: string;
          type: string;
        },
      ];
      appraisal_type: string;
      assessed_market_year: null | string;
      basement: null | string;
      building_size: number;
      business_name: string;
      city: string;
      client_id: number;
      close_date: null;
      comp_adjustment_mode: string;
      comp_area_map_zoom: null;
      comp_type: string;
      comparison_basis: string;
      comps_map_type: string;
      concessions: null;
      condition: string;
      conforming_use_determination: null;
      cost_comps_area_map_zoom: null;
      cost_comps_map_type: string;
      county: string;
      county_details_url: null;
      county_tax_url: null;
      created: string;
      data: null;
      date_of_analysis: null;
      date_sold: null;
      effective_date: null;
      electrical: null;
      exhibits: null;
      exterior: null;
      file_number: null;
      file_pdf_url: null;
      foundation: null;
      front_feet: string | number |  null;
      frontage: string;
      google_place_id: null;
      has_suite_parcel: null;
      heating_cooling: null;
      height: null;
      high_and_best_user: null;
      id: number;
      included_utilities: null;
      inspector_name: null;
      intended_use: null;
      intended_user: null;
      key_highlights: null;
      land_assessment: null | string;
      land_dimension: string;
      land_size: number;
      land_type: string;
      last_transfer_date_known: string;
      last_transferred_date: null;
      last_updated: string;
      latitude: string;
      lease_rate: null;
      linked_evals: null;
      longitude: string;
      lot_depth: null;
      lot_shape: string;
      main_structure_base: null;
      map_image_for_report_url: null;
      map_image_url: null;
      map_pin_image_url: null;
      map_pin_lat: string;
      map_pin_lng: string;
      map_pin_zoom: number;
      map_zoom: null;
      most_likely_owner_user: null;
      no_stories: string;
      other_include_utilities: string;
      owner_of_record: null;
      parcel_id_apn: string;
      parking: string;
      plumbing: null;
      position: string;
      price_square_foot: number;
      property_class: string;
      property_geocode: null;
      property_id: number;
      property_image_url: null;
      property_legal: null;
      property_rights: string;
      report_date: null;
      review_summary: null;
      roof: null;
      rounding: null;
      sale_price: null;
      services: null;
      sids: null;
      site_details_east: null;
      site_details_north: null;
      site_details_south: null;
      site_details_west: null;
      state: string;
      street_address: string;
      street_suite: string;
      structure_assessment: null | string;
      subdivision_survey_url: null;
      submitted: number;
      summary: string;
      tax_liability: null | string;
      tax_liability_year: null;
      taxes_in_arrears: null | string;
      term: null;
      topography: string;
      total_land_improvement: null;
      traffic_count: null;
      traffic_input: null;
      traffic_street_address: null;
      type: string;
      under_contract_price: null;
      user_id: number;
      utilities_select: string;
      utilities_text: null;
      weighted_market_value: null;
      windows: null;
      year_built: string;
      year_remodeled: string;
      zipcode: number;
      zoning_description: null;
      zoning_type: string;
      zonings: Zone[];
      property_rights_custom: string | null;
      most_likely_owner_user_custom: string | null;
      topography_custom: string | null;
      price: string | number;
    };
  };
}

export type Zone = {
  bed: string | number;
  unit: string | number;
  zone: number | string;
  sub_zone: string;
  sq_ft: string | number;
};
