export enum ResidentialComponentHeaderEnum {
  LOCATION = 'LOCATION DETAILS',
  PROPERTY = 'PROPERTY DETAILS',
  AMENITIES = 'AMENITIES DETAILS',
  SPACE = 'SPACE DETAILS',
  SITE = 'SITE DETAILS',
  BUILDING_DETAILS = 'BUILDING DETAILS',
  TRANSACTION = 'TRANSACTION DETAILS',
  MARK_COMP_PRIVATE = 'Mark this comp private',
  HEADER = 'CREATE COMP | OVERVIEW',
  GENERAL_INFORMATION = 'Lets get started! Enter some general information for this Comp.',
  GENERAL_INFORMATION_AP = 'Lets get started! Enter some general information for this Appraisal.',
  ADDITIONAL_AMENITIES = 'Additional Amenities',
  NO_ADDITIONAL_AMENITIES = 'No Additional Amenities',
  MARKING_COMP = ' Marking a comp as private means that only the person that created the comp will be able to view it or link it to an evaluation',
  INCLUDED_UTILITIES = 'included_utilities',
  SALES='sales',
  LEASES='leases',
  BUILDING_WITH_LAND='building_with_land',
  LAND_ONLY='land_only',
  SECTION='section',
  SCROLL='scroll',
 SMOOTH='smooth',
 STRING='string',
 MAP_ZOOM_RESIDENTIAL='mapZoomResidential',
 TRUE='true',
 FALSE='false',
 LOCATION_COMPONENT='LOCATION',
 PROPERTY_COMPONENT='PROPERTY',
AMENITIES_COMPONENT='AMENITIES',
TRANSACTION_COMPONENT='TRANSACTION',
SF='SF',
SELECT='select',
STUDIO='Studio',
NONE='None',
ALUMINIUM='Aluminum',
CLOSED='Closed',
UPDATE_COMP_OVERVIEW='UPDATE COMP | OVERVIEW',
BROKER_KEY='broker',
PROPERTY_KEY='property',
AMENITIES_KEY='amenities',
TRANSACTION_KEY='transaction',

}

export enum ButtonTitleEnum {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  ADD_NEW_PERSON = 'ADD NEW PERSON...',
  ADD_NEW_COMPANY = 'ADD NEW COMPANY...',
  ADD_MORE = 'ADD MORE',
  REMOVE = 'REMOVE',
  ADD_NEW = 'ADD NEW...',
}

export enum PrivateCompEnum {
  YES = 'Yes',
  NO = 'No',
}
export enum PropertyResidentialComp {
  PROPERTY_TYPE = 'Property Type',
  SUB_PROPERTY = 'Sub Property',
  GROSS_LIVING_AREA = 'Gross Living Area',
  BASEMENT_FININISHED = 'Basement Finished',
  BASEMENT_UNFINISHED = 'Basement Unfinished',
  SF_WEIGHTING = 'SF Weighting',
  SIZE_TYPE = 'Size Type',
  TOPOGRAPHY = 'Topography',
  LOT_SHAPE = 'Lot Shape',
  FRONTAGE = 'Frontage',
  CONDITION = 'Condition',
  BASEMENT = 'Basement',
  UTILITIES = 'Utilities',
  SUMMARY_NAME = 'summary',
  ZONINGS_NAME = 'zonings',
  BACKSPACE = 'Backspace',
  ACRE = 'ACRE',
  LAND_SIZE_NAME = 'land_size',
  LAND_DIMENSION_NAME = 'land_dimension',
  SF = 'SF',
  TOPOGRAPHY_NAME = 'topography',
  TOPOGRAPHY_CUSTOM = 'topograhpy_custom',
  LOT_SHAPE_NAME = 'lot_shape',
  LOT_SHAPE_CUSTOM = 'lot_shape_custom',
  FRONTAGE_NAME = 'frontage',
  FRONTAGE_CUSTOM = 'frontage_custom',
  CONDITION_NAME = 'condition',
  CONDITION_CUSTOM = 'condition_custom',
  YEAR_BUILT = 'year_built',
  YEAR_REMODELED = 'year_remodeled',
  BASEMENT_NAME = 'basement',
  BASEMENT_CUSTOM = 'basement_custom',
  UTILITIES_SELECT_NAME = 'utilities_select',
  UTILITIES_SELECT_CUSTOM = 'utilities_select_custom',
  ZONING_TYPE = 'zoning_type',
  ZONE = 'zone',
  SUB_ZONE = 'sub_zone',
  RESIDENTIAL = 'residential',
  GROSS_LIVING_SQ_FT = 'gross_living_sq_ft',
  BASEMENT_FINISHED_SQ_FT = 'basement_finished_sq_ft',
  BASEMENT_UNFINISHED_SQ_FT = 'basement_unfinished_sq_ft',
  WEIGHT_SF = 'weight_sf',
  SUB_ZONE_CUSTOM = 'sub_zone_custom',
  PROPERTY_SUMMARY = 'Property Summary',
  OTHER_SUB_ZONE = 'Other Sub Property Type',
  LAND_SIZE = 'Land Size',
  OTHER_TOPOGRAPHY = 'Other Topography',
  OTHER_LOT_SHAPE = 'Other Lot Shape',
  OTHER_FRONTAGE = 'Other Frontage',
  OTHER_CONDITION = 'Other Condition',
  BUILT_YEAR = 'Built Year',
  REMODELED_YEAR = 'Remodeled Year',
  OTHER_BASEMENT = 'Other Basement',
  OTHER_UTILITIES = 'Other Utilities',
  ZONING_TYPE_LABEL = 'Zoning Type',
  RESIDENTIAL_PROPERTY_TYPE='Other Subzone'
}

export enum AmenitisResidentialComp {
  EXTERIOR = 'Exterior',
  ROOF = 'Roof',
  ELECTRICAL = 'Electrical',
  PLUMBING = 'Plumbing',
  HEATING_COOLING = 'Heating/Cooling',
  WINDOWS = 'Windows',
  BEDROOMS = 'Bedrooms',
  BATHROOMS = 'Bathrooms',
  GARAGE = 'Garage',
  FENCING = 'Fencing',
  FIREPLACE = 'Fireplace',
  TYPE_MY_OWN = 'Type My Own',
  EXTERIOR_NAME = 'exterior',
  EXTERIOR_CUSTOM = 'exterior_custom',
  ROOF_NAME = 'roof',
  ROOF_CUSTOM = 'roof_custom',
  ELECTRICAL_NAME = 'electrical',
  ELECTRICAL_CUSTOM = 'electrical_custom',
  PLUMBING_NAME = 'plumbing',
  PLUMGING_CUSTOM = 'plumbing_custom',
  HEATING_COOLING_NAME = 'heating_cooling',
  HEATING_COOLING_CUSTOM = 'heating_cooling_custom',
  WINDOWS_NAME = 'windows',
  WINDOWS_CUSTOM = 'windows_custom',
  BEDROOMS_NAME = 'bedrooms',
  BEDROOMS_CUSTOM = 'bedrooms_custom',
  BATHROOMS_NAME = 'bathrooms',
  BATHROOMS_CUSTOM = 'bathrooms_custom',
  GARAGE_NAME = 'garage',
  GARAGE_CUSTOM = 'garage_custom',
  FENCING_NAME = 'fencing',
  FENCING_CUSTOM = 'fencing_custom',
  FIREPLACE_NAME = 'fireplace',
  FIREPLACE_CUSTOM = 'fireplace_custom',
  OTHER_AMENITIES = 'other_amenities',
  OTHER_EXTERIOR = 'Other Exterior',
  OTHER_ROOF = 'Other Roof',
  OTHER_ELECTRICAL = 'Other Electrical',
  OTHER_PLUMBING = 'Other Plumbing',
  OTHER_HEATING_COOLING = 'Other Heating/Cooling',
  OTHER_WINDOWS = 'Other Windows',
  OTHER_BEDROOMS = 'Other Bedrooms',
  OTHER_BATHROOMS = 'Other Bathrooms',
  OTHER_GARAGE = 'Other Garage',
  OTHER_FENCING = 'Other Fencing',
  OTHER_FIREPLACE = 'Other Fireplace',
  OTHER_AMENITIES_LABEL = 'Other Amenities',
}
export enum LocationResidentialComp {
  PROPERTY_TYPE = 'Property Name',
  CITY = 'City',
  ZIPCODE = 'Zipcode',
  CITY_NAME = 'city',
  ZIPCODE_NAME = 'zipcode',
  PROPERTY_NAME = 'property_name',
  STREET_SUITE_NAME = 'street_suite',
  STREET_ADDRESS_NAME = 'street_address',
  LATITUDE = 'latitude',
  LONGITUDE = 'longitude',
  STATE_NAME = 'state',
  GEOMETRY = 'geometry',
  SELECT_STATE = 'State',
}
export enum TransactionResidentialComp {
  SALE_PRICE = 'Sale Price',
  DATE_SOLD = 'Date Sold',
  SALE_STATUS = 'Sale Status',
  LIST_DATE = 'List Date',
  SALE_PRICE_NAME = 'sale_price',
  DATE_SOLD_NAME = 'date_sold',
  SALE_STATUS_NAME = 'sale_status',
  LIST_PRICE = 'List Price',
  LIST_PRICE_NAME = 'list_price',
  DATE_LIST = 'date_list',
  DAYS_ON_MARKET = 'Days on Market',
  DAYS_ON_MARKET_NAME = 'days_on_market',
  TOTAL_CONCESSIONS = 'Total Concessions',
  TOTAL_CONCESSIONS_NAME = 'total_concessions',
}

export enum ResidentialRoute {
  RESIDENTIAL_CREATE_COMPS = '/residential-create-comps',
  RES_COMPS = 'res_comps',
  RES_COMPS_VIEW = 'res-comps-view',
  RESIDENTIAL_UPDATE_COMPS = 'residential-update-comps',
}
