export interface RescompsGetDataType{
    data:{
        data:{
            account_id:number | undefined,
            acquirer_id:number | undefined,
            acquirer_type:string | undefined,
            basement:string | undefined,
            bathrooms:string | undefined,
            bedrooms:string | undefined,
            building_size:number | undefined,
            city:string | undefined,
            condition:string | undefined,
            county:string | undefined,
            created:string | undefined,
            date_list:string | undefined,
            date_sold:string | undefined,
            days_on_market:number | undefined,
            electrical:string | undefined,
            exterior:string | undefined,
            fencing:string | undefined,
            fireplace:string | undefined,
            frontage:string | undefined,
            garage:string | undefined,
            heating_cooling:string | undefined,
            id:number | undefined,
            land_dimension:string | undefined,
            land_size:number | undefined,
            last_updated:string | undefined,
            latitude:string | undefined,
            list_price:number | undefined,
            longitude:string | undefined,
            lot_shape:string | undefined,
            map_pin_lat:string | undefined,
            map_pin_lng:string | undefined,
            map_pin_zoom:number | undefined,
            offeror_id:number | undefined,
            offeror_type:string | undefined,
            other_amenities:string | undefined,
            plumbing:string | undefined,
            price_square_foot:number | undefined,
            private_comp:number | undefined,
            property_id:number | undefined,
            property_image_url:string,
            property_name:string,
            res_comp_amenities:[{
                additional_amenities:string,
                date_created:string,
                id:number,
                last_updated:string,
                res_comp_id:number,
            }],
            res_zonings:[],
            roof:string | undefined,
            sale_price:number | undefined,
            sale_status:string | undefined,
            state:string | undefined,
            street_address:string | undefined,
            summary:string | undefined,
            topography:string | undefined,
            total_concessions:number | undefined,
            type:string | undefined,
            user_id:number | undefined,
            utilities_select:string | undefined,
            utilities_text:null,
            windows:string | undefined,
            year_built:string | undefined,
            year_remodeled:string | undefined,
            zipcode:number | undefined,
            zoning_type:string | undefined,
        }
    }
}