export enum ListingHeaderEnum {
  COMPS_LIST = 'COMP LIST',
  UPLOAD = 'Upload',
  ADD_NEW = 'Add New',
  LISTING = 'Listing',
  FILTERS = 'Filters',
}

export enum PaginationEnum {
  NEXT = 'Next',
  PREVIOUS = 'Previous',
}

export enum ListingEnum {
  LEASES = 'Lease',
  SALES = 'Sale',
  N0_RECORDS_FOUND = 'No Records Found',
  SOLD = 'Sold',
  TYPE = 'Type',
  // PROPERTY_TYPES='Type',
  SALE_DATE = 'Sale Date',
  CAP_RATE = 'CAP Rate',
  LAND_SIZE = 'Land Size',
  BUILDING_SIZE = 'Building Size',
  LEASE_RATE = 'Lease Rate : ',
  SALES_PRICE = 'Sales Price : $',
  VIEW = 'View',
  LOADING = 'Loading',
  ERROR = 'ERROR',
  DATE_SOLD = 'date_sold',
  PROPERTY_TYPE = 'propertyType',
  SALE = 'sale',
  LEASE = 'lease',
  BUILDING_WITH_LAND = 'Building(s) with Land',
  LAND_ONLY = 'Land Only',
  SF = '$/SF : ',
  ACRE = '$/ACRE : ',
  NA = 'N/A',
  TOTAL_PROPERTIES = 'Total Properties',
  EDIT = 'Edit',
  COMP_TYPE = 'comp_type',
  YEAR_BUILT_REMODELED = 'Year Built/Remodeled',
  BED_BATH = 'Bed/Bath',
  ZONING = 'Zoning',
}

export enum DeleteCompEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this comp will be lost.',
  DELETE_COMP = 'Delete Comp',
  CANCEL = 'Cancel',
}
export enum ChangeRentRoll {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = ' Switching view will clear all your data. Are you sure you want to proceed?',
  OK = 'OK',
  CANCEL = 'Cancel',
}
export enum DeleteAppraisalEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this appraisal will be lost.',
  DELETE_COMP = 'Delete Appraisal',
  CANCEL = 'Cancel',
}
export enum DeleteTemaplateEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this template will be lost.',
  DELETE_COMP = 'Delete Template',
  CANCEL = 'Cancel',
}
export enum DeleteSectionItemEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this item.',
  DELETE_COMP = 'Delete Item',
  CANCEL = 'Cancel',
}
export enum DeleteSnippetItemEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this snippet.',
  DELETE_SNIPPET = 'Delete Snippet',
  CANCEL = 'Cancel',
}

export enum DeleteEvalutionPhotoEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this row.',
  DELETE_SNIPPET = 'Delete',
  CANCEL = 'Cancel',
}
export enum CreateCompsEnum {
  DATE_SOLD = 'Date Sold',
  DATE_START = 'Sale Start Date',
  DATE_END = 'Sale End Date',
  LEASE_DATE_START = 'Lease Date Start',
  LEASE_DATE_END = 'Lease Date End',
  SALE_PRICE = 'Sale Price',
  CONDITION = 'Condition',
  TRANSACTION_DATE = 'Transaction Date',
  LEASE_TYPE = 'Lease Type',
  LEASE_RATE = 'Lease Rate',
  LEASE_RATE_UNITS = 'Lease Rate Units',
  LEASE_STATUS = 'Lease Status',
  TI_ALLOWANCE = 'TI Allowance Units',
  ASKING_RATE = 'Asking Rent Units',
  LAND_TYPE = 'Land Type',
  SIZE_TYPE = 'Size Type',
  TOPOGRAPHY = 'Topography',
  LOT_SHAPE = 'Lot Shape',
  FRONTAGE = 'Frontage',
  UTILITIES = 'Utilities',
  STREET_ADDRESS = 'Street Address',
  REMOVE = 'remove',
  PROPERTY_NAME = 'Property Name',
  CITY = 'City',
  STATE = 'State',
  ZIPCODE = 'Zipcode',
  REQUIRED_FIELD = 'This field is required',
  PARKING = 'Parking',
  INCLUDED_UTILITIES = 'No Included Utilities',
  ADD_IMAGE = 'Add Image',
  PROPERTY_ON = 'This Property is on',
  COMPARISON_BASIS = 'Comparison Basis',
  BUILDING_WITH_LAND = 'Building With Land',
  PROPERTY_TYPE = 'Property Type',
  SUB_PROPERTY = 'Sub Property',
  SQ_FT = 'SQ.FT.',
}

export enum BuildingDetailsEnum {
  MULTIFAMILY = 'multi_family',
  RESIDENTIAL = 'residential',
  HOSPITALITY = 'hospitality',
  OFFICE = 'office',
  RETAIL = 'retail',
  INDUSTRIAL = 'industrial',
  SPECIAL = 'special',
  PARKING_CUSTOM = 'parking_custom',
  COMPARISON_BASIS = 'comparison_basis',
  PARKING = 'parking',
  CONDITION_CUSTOM = 'condition_custom',
  CONDITION = 'condition',
  BUILDING_COMMENTS = 'building_comments',
  EFFECTIVE_AGE = 'effective_age',
  STORIES = 'stories',
  CONSTRUCTION_CLASS = 'construction_class',
  YEAR_REMODELED = 'year_remodeled',
  YEAR_BUILT = 'year_built',
  NET_BUILDING_AREA = 'net_building_area',
  GROSS_BUILDING_AREA = 'gross_building_area',
  SF = 'SF',
  UNIT = 'Unit',
  Bed = 'Bed',
}

export enum SellerBuyierEnum {
  MARK_COMP_PRIVATE = 'Mark this comp private',
  NAME = 'Name',
  PERSON = 'person',
  COMPANY = 'company',
  ADD_NEW_PERSON = 'Add New Person...',
  ADD_NEW_COMPANY = 'Add New Company...',
  ADD_NEW = 'Add New...',
  SELLER_TYPE = 'Seller Type',
  LANDLORD_TYPE = 'Landlord Type',
  BUYER_TYPE = 'Buyer Type',
  PLZ_SELECT_TYPE_FIRST = 'Please Select Type First',
  OFFEROR_TYPE = 'offeror_type',
  ACQUIRE_TYPE = 'acquirer_type',
  OFFEROR_ID = 'offeror_id',
  ACQUIRE_ID = 'acquirer_id',
  SELECT_PERSON = '--Select Person--',
  SELECT_COMPANY = '--Select Company--',
  PRIVATE_COMP = 'private_comp',
  SELECT = 'select',
  UPDATE = 'update',
  CREATE = 'create',
  PLZ_COMPLETE_MISSING_FIELD = 'Please complete the missing fields',
}

export enum FilterListingEnum {
  SEARCH_TYPE = 'SEARCH TYPE',
  SEARCH = 'SEARCH',
  LOCATION = 'LOCATION',
  ADVANCE_FILTER = 'ADVANCED FILTER',
  SORT_BY = 'Sort by',
  SALE_DATE_END = 'Sale Date End',
  APPLY = 'APPLY',
  MAP_SEARCH_FILTER = 'MapSearchFilter',
  DESC = 'DESC',
  ASC = 'asc',
  CITY = 'city',
  ADDITIONAL_CRITERIA = 'ADDITIONAL CRITERIA',
  SALE_DATE_START = 'Sale Date Start',
  DATE_SOLD = 'date_sold',
  LINK_SELECTED_COMPS = 'Link Selected Comps',
  ADJUST_SEARCH = 'Adjust Search',
  CLOSE = 'Close',
}

export enum MenuOptionsEnum {
  ANDROID = 'android',
  SEARCH_LISTINGS = 'Search Comps',
  PROPERTY_TYPE = 'Property Type',
  LIST_RESI = 'list-resi',
  LAND_ONLY = 'land_only',
  BUILDING_WITH_LAND = 'building_with_land',
}

export enum SortingEnum {
  Date_SOLD = 'date_sold',
  BUSINESS_NAME = 'business_name',
  STREET_ADDRESS = 'street_address',
  SALE_PRICE = 'sale_price',
  LEASE_RATE = 'lease_rate',
  PROPERTY_TYPE = 'property_name',
  ASC = 'asc',
  ASC_0 = 'asc_0',
  ASC_1 = 'asc_1',
  DESC = 'desc',
  DESC_0 = 'DESC_0',
  DESC_1 = 'DESC_1',
}

export enum SiteDetailsEnum {
  LAND_SIZE_SITE = 'land_size',
  LAND_DIMENSION = 'land_dimension',
  OTHER_TOPOGRAPHY = 'other_topography',
  LOT_SHAPE = 'lot_shape',
  FRONTAGE_SITE = 'frontage',
  FRONTAGE_CUSTOM = 'frontage_custom',
  SITE_ACCESS = 'site_access',
  UTILITIES_SELECT = 'utilities_select',
  OTHER_UTILITY = 'other_utility',
  SITE_COMMENTS = 'site_comments',
  TOPOGRAPHY_CUSTOM = 'topography_custom',
  TOPOGRAPHY = 'topography',
  UTILITIES_SELECT_CUSTOM = 'utilities_select_custom',
  LOT_SHAPE_CUSTOM = 'lot_shape_custom',
  OTHER_INCLUDED_UTILITIES = 'other_include_utilities',
  LAND_TYPE = 'land_type',
  LAND_TYPE_CUSTOM = 'land_type_custom',
}

export enum DeleteModalLabelEnum {
  DELETE_EXHIBIT = 'Delete Exhibit',
  DELETE_LIST = 'Delete List',
}
