export const ExteriorOptions = [
  { value: 'Wood Siding', label: 'Wood Siding' },
  { value: 'Steel', label: 'Steel' },
  { value: 'Wood', label: 'Wood' },
  { value: 'Glass', label: 'Glass' },
  { value: 'Brick', label: 'Brick' },
  { value: 'Masonry', label: 'Masonry' },
  { value: 'Concrete Block', label: 'Concrete Block' },
  { value: 'Masonry with Block Back Up', label: 'Masonry with Block Back Up' },
  { value: 'Concrete Board and Masonry', label: 'Concrete Board and Masonry' },
  { value: 'Masonry and EEIS exterior', label: 'Masonry and EFIS exterior' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const RoofOptions = [
  { value: 'Standing Seam Metal', label: 'Standing Seam Metal' },
  { value: '60mil TPO Membrane', label: '60mil TPO Membrane' },
  { value: 'EPDM Membrane', label: 'EPDM Membrane' },
  { value: 'Asphalt Shingle', label: 'Asphalt Shingle' },
  { value: 'Tar and Gravel', label: 'Tar and Gravel' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const ElectricalOptions = [
  { value: 'Single Phase', label: 'Single Phase' },
  { value: 'Three Phase', label: 'Three Phase' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const PlumbingOptions = [
  { value: 'No Plumbing', label: 'No Plumbing' },
  { value: 'Average per Code', label: 'Average per Code' },
  { value: 'Above Average', label: 'Above Average' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const HeatingCoolingOptions = [
  { value: 'GFA with Cooling', label: 'GFA with Cooling' },
  { value: 'GFA without Cooling', label: 'GFA without Cooling' },
  { value: 'Infrared Gas Radiant Tube', label: 'Infrared Gas Radiant Tube' },
  { value: 'HVAC System', label: 'HVAC System' },
  { value: 'Boiler & Chiller System', label: 'Boiler & Chiller System' },
  { value: 'Electric', label: 'Electric' },
  { value: 'In Floor Radiant Heating', label: 'In Floor Radiant Heating' },
  { value: 'No Heating', label: 'No Heating' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const WindowOptions = [
  { value: 'Insulated Double Pane', label: 'Insulated Double Pane' },
  { value: 'Insulated & Cased', label: 'Insulated & Cased' },
  { value: 'Single Pane', label: 'Single Pane' },
  { value: 'No Windows', label: 'No Windows' },
  { value: 'Mix of Old & New', label: 'Mix of Old & New' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const BedroomOptions = [
  { value: 'studio', label: 'Studio' },
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
  { value: '11', label: '11' },
  { value: '12', label: '12' },
  { value: '13', label: '13' },
  { value: '14', label: '14' },
  { value: '15', label: '15' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const BarthroomOptions = [
  { value: '0', label: '0' },
  { value: '0.5', label: '0.5' },
  { value: '1', label: '1' },
  { value: '1.5', label: '1.5' },
  { value: '2', label: '2' },
  { value: '2.5', label: '2.5' },
  { value: '3', label: '3' },
  { value: '3.5', label: '3.5' },
  { value: '4', label: '4' },
  { value: '4.5', label: '4.5' },
  { value: '5', label: '5' },
  { value: '5.5', label: '5.5' },
  { value: '6', label: '6' },
  { value: '6.5', label: '6.5' },
  { value: '7', label: '7' },
  { value: '7.5', label: '7.5' },
  { value: '8', label: '8' },
  { value: '8.5', label: '8.5' },
  { value: '9', label: '9' },
  { value: '9.5', label: '9.5' },
  { value: '10', label: '10' },
  { value: '10.5', label: '10.5' },
  { value: '11', label: '11' },
  { value: '11.5', label: '11.5' },
  { value: '12', label: '12' },
  { value: '12.5', label: '12.5' },
  { value: '13', label: '13' },
  { value: '13.5', label: '13.5' },
  { value: '14', label: '14' },
  { value: '14.5', label: '14.5' },
  { value: '15', label: '15' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const GarageOptions = [
  { value: 'None', label: 'None' },
  { value: 'Single Car Detached', label: 'Single Car Detached' },
  { value: 'Single Car Attached', label: 'Single Car Attached' },
  { value: 'Two Car Detached', label: 'Two Car Detached' },
  { value: 'Two Car Attached', label: 'Two Car Attached' },
  { value: 'Three Car Detached', label: 'Three Car Detached' },
  { value: 'Three Car Attached', label: 'Three Car Attached' },
  { value: 'Four Car Detached', label: 'Four Car Detached' },
  { value: 'Four Car Attached', label: 'Four Car Attached' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const FencingOptions = [
  { value: 'Aluminum', label: 'Aluminum' },
  { value: 'Wood', label: 'Wood' },
  { value: 'PVC', label: 'PVC' },
  { value: 'Wrought Iron', label: 'Wrought Iron' },
  { value: 'Vinyl', label: 'Vinyl' },
  { value: 'Chain Link', label: 'Chain Link' },
  { value: 'Electric', label: 'Electric' },
  { value: 'Barbed Wire', label: 'Barbed Wire' },
  { value: 'None', label: 'None' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const FireplaceOptions = [
  { value: '0', label: '0' },
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: 'Type My Own', label: 'Type My Own' },
];
export const AddtitionalAmenitiesOptions = [
  { value: 'Patio (Uncovered)', label: 'Patio (Uncovered)' },
  { value: 'Patio (Covered)', label: 'Patio (Covered)' },
  { value: 'Deck (Uncovered)', label: 'Deck (Uncovered)' },
  { value: 'Deck (Covered)', label: 'Deck (Covered)' },
  { value: 'Underground Sprinklers', label: 'Underground Sprinklers' },
  { value: 'Shed', label: 'Shed' },
  { value: 'Pool', label: 'Pool' },
  { value: 'Hot Tub', label: 'Hot Tub' },
  { value: 'Outdoor Kitchen', label: 'Outdoor Kitchen' },
  { value: 'Landscaping', label: 'Landscaping' },
];

export const PropertyOptions = [
  { value: '', label: '--Select Property Type--' },
  { value: 'residential', label: 'Residential' },
];

export const BasementOptions = [
  { value: 'None', label: 'None' },
  { value: 'Partial', label: 'Partial' },
  { value: 'Full', label: 'Full' },
  { value: 'Daylight', label: 'Daylight' },
  { value: 'Type My Own', label: 'Type My Own' },
];
