export enum ListingHeaderEnum {
  COMPS_LIST = 'COMP LIST',
  UPLOAD = 'Upload',
  IMPORT = 'Import',
  ADD_NEW = 'Add New',
  LISTING = 'Listing',
  FILTERS = 'Filters',
  IMPORT_COMP = 'Import Comp',
}

export enum PaginationEnum {
  NEXT = 'Next',
  PREVIOUS = 'Previous',
}

export enum ListingEnum {
  LEASES = 'Lease',
  SALES = 'Sale',
  N0_RECORDS_FOUND = 'No Records Found',
  SOLD = 'Sold',
  TYPE = 'Type',
  // PROPERTY_TYPES='Type',
  SALE_DATE = 'Sale Date',
  CAP_RATE = 'CAP Rate',
  LAND_SIZE = 'Land Size',
  
 
  BUILDING_SIZE_AND_LAND_SIZE = 'building_size_land_size',
  SUITE_SIZE = 'Suite Size',
  BUILDING_SIZE_LAND_SIZE = 'Building Size / Land Size',
  BUILDING_SIZE = 'Building Size',
  LEASE_RATE = 'Lease Rate : ',
  SALES_PRICE = 'Sale Price : $',
  LOT = 'Lot',
  VIEW = 'View',
  LOADING = 'Loading',
  ERROR = 'ERROR',
  DATE_SOLD = 'date_sold',
  PROPERTY_TYPE = 'propertyType',
  SALE = 'sale',
  LEASE = 'lease',
  BUILDING_WITH_LAND = 'Building(s) with Land',
  LAND_ONLY = 'Land Only',
  SF = '$/SF : ',
  PER_SF = '/SF',
  ACRE = '$/ACRE : ',
  NA = 'N/A',
  TOTAL_PROPERTIES = 'Total Properties',
  EDIT = 'Edit',
  COMP_TYPE = 'comp_type',
  YEAR_BUILT_REMODELED = 'Year Built/Remodeled',
  BED_BATH = 'Bed/Bath',
  ZONING = 'Zoning',
  CONDITION = 'Condition',
  SERVICES_ = 'Services',
  SERVICES = 'services',

  SELECT_ALL = 'Select all',
  PRINT = 'Print',
  TRUE = 'true',
  ZERO = 0,
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
  SEVEN = 7,
  EIGHT = 8,
  TEN = 10,
  TWELVE = 12,
  FIFTEEN = 15,
  FORTY = 40,
  SIXTY = 60,
  HUNDRED = 100,
  TWO_HUNDRED = 200,
  THREE_HUNDRED = 300,
  FOUR_HUNDRED = 400,
  ONE_THOUSAND = 1000,
  TWO_THOUSAND = 2000,
  SQFT_ACRE = 43560,
  TEN_LAKH = 1000000,
  STATE = 'state',
  LATITUDE = 'latitude',
  LONGITUDE = 'longitude',
  MONTHLY = 'monthly',
  DOLLAR = 'Dollar',
  UNDEFINED = 'undefined',
  LEASE_ID = 'leaseId',
  COVER = 'cover',
  ALL = 'all',
  SALES_COMP_QUALITATIVE_ADJUSTMENT = 'sales_comp_qualitative_adjustments',
  SALES_COMP_QUANTITATIVE_ADJUSTMENT = 'sales_comp_quantitative_adjustments',
  SALES_RES_COMP_QUANTITATIVE_ADJUSTMENTS = 'sales_res_comp_quantitative_adjustments',
  LEASE_QUANTITATIVE_ADJUSTMENTS = 'lease_quantitative_adjustments',
  TIME = 'time',
  TIME_CAPITAL = 'Time',
  OPERATING_EXP = 'operating_exp',
  OPERATING_EXPENSES = 'Operating Expenses',
  CONSTRUCTION = 'construction',
  CONSTRUCTION_CAPITAL = 'Construction',
  ECONOMIES_OF_SCALE = 'economies_of_scale',
  ECONOMIES_OF_SCALE_ = 'Economies Of Scale',
  SIMILAR = 'similar',
  SIMILAR_ = 'Similar',
  ERROR_FETCHIN_DATA = 'Error fetching comps data:',
  ERROR_FETCHIN_RENT_DATA = 'Error fetching rent roll data:',
  ERROR_OCCURED_TRY_AGAIN = 'An error occurred. Please try again.',
  MAXIMUM_FOUR_COMPS = 'Maximum of 4 comps allowed. Cannot add more comps.',
  SELECT_A_SUBTYPE = '--Select a Subtype--',
  SELECT_PROPERTY_CONDITIONS = '--Select Property Condition--',
  ADD_NOTES = 'Click to add notes',
  CLICK_TO_ADD = 'Click to add',
  TABLE_DATA = 'tableData',
  CAP_RATE_COMPS = 'Cap Rate comps',
  VALUE_OF_PROPERTY_ON_APPLICABLE_CAP_RATE = 'Value of the property based on applicable CAP Rate comps.',
  MULTI_FAMILY_APPROACH = 'MULTI FAMILY APPROACH',
  INVALID_DATA_STRUCTURE_RECEIVED = 'Invalid data structure received',
  LOADING_PROPERTY_DETAILS = 'Loading property details...',
  LOADING_GOOGLE_MAPS = 'Loading Google Maps...',
  PROPERTY_DETAIL_NOT_AVAILABLE = 'Property details not available',
  CLICK_TO_CLOSE = 'Click to close',
}

export enum DeleteCompEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this comp will be lost.',
  DELETE_COMP = 'Delete Comp',
  CANCEL = 'Cancel',
}
export enum ChangeRentRoll {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = ' Switching view will clear all your data. Are you sure you want to proceed?',
  OK = 'OK',
  CANCEL = 'Cancel',
}
export enum DeleteAppraisalEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this appraisal will be lost.',
  DELETE_COMP = 'Delete Appraisal',
  CANCEL = 'Cancel',
}
export enum DeleteTemaplateEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this template will be lost.',
  DELETE_COMP = 'Delete Template',
  CANCEL = 'Cancel',
}
export enum DeleteSectionItemEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this item.',
  DELETE_COMP = 'Delete Item',
  CANCEL = 'Cancel',
}
export enum DeleteSnippetItemEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this snippet.',
  DELETE_SNIPPET = 'Delete Snippet',
  CANCEL = 'Cancel',
}

export enum DeleteEvalutionPhotoEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. Are you sure you want to delete this row.',
  DELETE_SNIPPET = 'Delete',
  CANCEL = 'Cancel',
}
export enum DeleteEvaluationEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. All data associated with this evaluation will be lost.',
  DELETE_EVALUATION = 'DELETE EVALUATION',
  CANCEL = 'Cancel',
}

export enum DeleteImageEnum {
  ARE_YOU_SURE = 'Are you sure?',
  WARNING_MESSAGE = 'This action can not be undone. This image will be permanently deleted.',
  DELETE_IMAGE = 'Delete Image',
  CANCEL = 'Cancel',
}
export enum CreateCompsEnum {
  COST_COMPS = 'COST COMPS',
  DATE_SOLD = 'Date Sold',
  DATE_START = 'Sale Start Date',
  DATE_END = 'Sale End Date',
  LEASE_DATE_START = 'Lease Date Start',
  LEASE_DATE_END = 'Lease Date End',
  SALE_PRICE = 'Sale Price',
  CONDITION = 'Condition',
  TRANSACTION_DATE = 'Transaction Date',
  Transaction_date = 'transaction_date',
  LEASE_TYPE = 'Lease Type',
  LEASE_TERMS_MONTHS = 'Lease Terms - Months',
  LEASE_RATE = 'Lease Rate',
  LEASE_RATE_UNITS = 'Lease Rate Units',
  LEASE_STATUS = 'Lease Status',
  TI_ALLOWANCE = 'TI Allowance Units',
  ASKING_RATE = 'Asking Rent Units',
  LAND_TYPE = 'Land Type',
  PROPERTY_TYPE_SUB_TYPE = 'Property Type/Sub-Type',
  YEAR_BUILT_REMODELED = 'Year Built / Remodeled',
  SIZE_TYPE = 'Size Type',
  TOPOGRAPHY = 'Topography',
  LOT_SHAPE = 'Lot Shape',
  FRONTAGE = 'Frontage',
  UTILITIES = 'Utilities',
  STREET_ADDRESS = 'Street Address',
  REMOVE = 'remove',
  PROPERTY_NAME = 'Property Name',
  CITY = 'City',
  STATE = 'State',
  ZIPCODE = 'Zipcode',
  REQUIRED_FIELD = 'This field is required',
  PARKING = 'Parking',
  INCLUDED_UTILITIES = 'No Included Utilities',
  INCLUDE_UTILITIES = 'Included Utilities',
  ADD_IMAGE = 'Add Image',
  PROPERTY_ON = 'This Property is on',
  COMPARISON_BASIS = 'Comparison Basis',
  BUILDING_WITH_LAND = 'Building With Land',
  PROPERTY_TYPE = 'Property Type',
  SUB_PROPERTY = 'Sub Property',
  SQ_FT = 'SQ.FT.',

  ADD_COMPS = 'Add Comps',
  ADD_NEW_COMP = 'Add New Comp',
  LEASE_NOTES = 'Lease Notes',
  SALES_COMPS = 'Sales comps',
  CAP_COMPS_NOTES = 'CAP Comps Notes',
  LINK_EXISTING_COMPS = 'Link Existing Comps',
  NOTES = 'Notes',
  OVERALL_ADJUSTMENT = 'Overall Adjustment',
  OVERVIEW = 'Overview',
  OVERVIEW_PAGE = 'Overview Page',
  PHOTO_PAGES = 'Photo Pages',
  IMAGES_PAGE = 'Images Page',
  MAP_BOUNDARY_PAGE = 'Map Boundary Page',
  AERIAL_MAP = 'Aerial Map',
  AREA_INFO = 'Area Info',
  INCOME_APPROACH = 'Income Approach',
  ADJUSTED_SALE_PRICE = 'Adjusted Sale Price',
  TOTAL_LAND_VALUE = 'Total Land Value',
  SUBJECT_PROPERTY = 'Subject Property',
  WEIGHTING = 'Weighting',
  ADJUSTED_DOLLAR_PER_SF = 'Adjusted $/SF',
  ADJUSTED_DOLLAR_PER_ACRE = 'Adjusted $/ACRE',
  NO_OPERATING_EXPENSES = 'No operating expenses data',
  NO_APPRAISAL = 'No appraisal specific adjustment data',
  VALUE_OF_LAND = 'Value of the land based on applicable land comps.',
  VALUE_OF_PROPERTY = 'Value of the property based on applicable sales comps',
  NO_SALES_COMP_DATA = 'No sales comp qualitative adjustment data',
  OVERALL_COMPARABILITY = 'Overall Comparability',
  ADJUSTED_PRICE_PER_BED = 'Adjusted Price Per Bed',
  ADJUSTED_PRICE_PER_UNIT = 'Adjusted Price Per Unit',
  ADJUSTED_PRICE_PER_ACRE = 'Adjusted Price Per Acre',
  ADJUSTED_PRICE_PER_SF = 'Adjusted Price Per SF',
  SALES_VALUE_PER_BED = 'Sales Value $/Bed',
  SALES_VALUE_PER_UNIT = 'Sales Value $/Unit',
  SALES_VALUE_PER_ACRE = 'Sales Value $/Acre',
  SALES_VALUE_PER_SF = 'Sales Value $/SF',
  AVERAGE_ADJUSTED_PRICE_PER_SF = 'Average Adjusted $/SF',
  TOTAL_SALES_VALUE = 'Total Sales Value',
  NO_DATA = 'No data',
  CLICK_ENTER_PROPERTY_NOTES = 'Click to Enter Property Notes',
  SALES_PRICE = 'Sales Price',
  LOCATION = 'Location',
  LOCATION_LOWER = 'location',
  FT = 'ft.',
  COMPS_DOWNLOADED_SUCCESSFULLY = 'Comps downloaded successfully!',
  ERROR_DOWNLOADING_COMPS = 'Error downloading comps:',
  FAILED_TO_DOWNLOAD_COMPS = 'Failed to download comps',
  PLEASE_SELECT_COMPS = 'Please select Comps',
  UPLOAD_AS_NEW = 'Upload as new',
  LEASE_COMPS = 'Lease comps',
  VALUE_LEASE_COMPS = 'Value of the property based on applicable Lease comps',
  DATE_LEASED = 'Date Leased',
  ADJUSTED_DOLLAR_PER_BED = 'Adjusted $/Bed',
  ADJUSTED_DOLLAR_PER_UNIT = 'Adjusted $/Unit',
  ADJUSTED_DOLLAR_PER_AC = 'Adjusted $/AC',
  ADJUSTED_COMP_RANGE = 'Adjusted Comp Range',
  ENSURE_WEIGHTAGE_HUNDRED_PERCENT = 'Please ensure total weightage remains 100%',
  ADD_ADJUSTMENT_NOTES = 'Click to add adjustment notes',
  RENTAL_RATES_DOLLAR_PER_MONTH = 'Rental Rates $/Mo.',
  ADJUSTED_RENTAL_RATES = 'Adjusted Rental Rates $Mo',
  DOLLAR_BEDS = '$/Beds',
  DOLLAR_PER_UNIT = '$/Unit',
  DOLLAR_AC_YEAR = '$/AC/Year',
  DOLLAR_PER_SF_YR = '$/SF/YR',
}

export enum BuildingDetailsEnum {
  MULTIFAMILY = 'multi_family',
  RESIDENTIAL = 'residential',
  HOSPITALITY = 'hospitality',
  OFFICE = 'office',
  RETAIL = 'retail',
  INDUSTRIAL = 'industrial',
  SPECIAL = 'special',
  PARKING_CUSTOM = 'parking_custom',
  COMPARISON_BASIS = 'comparison_basis',
  PARKING = 'parking',
  CONDITION_CUSTOM = 'condition_custom',
  CONDITION = 'condition',
  BUILDING_COMMENTS = 'building_comments',
  EFFECTIVE_AGE = 'effective_age',
  STORIES = 'stories',
  CONSTRUCTION_CLASS = 'construction_class',
  YEAR_REMODELED = 'year_remodeled',
  YEAR_BUILT = 'year_built',
  NET_BUILDING_AREA = 'net_building_area',
  GROSS_BUILDING_AREA = 'gross_building_area',
  SF = 'SF',
  UNIT = 'Unit',
  UNITS = 'Units',
  WEIGHTED_TOTAL = 'Weighted Total',
  Bed = 'Bed',
  BEDS = 'Beds',
  PER_BED = ' / Bed',
  SALES = 'Sales',
  INCOME = 'income',
  INCOME_ = 'Income',
  RENT_ROLL = 'Rent Roll',
  SALES_APPROACH = 'Sales Approach',
  LEASE_APPROACH = 'Lease Approach',
  COST = 'cost',
  COST_ = 'Cost',
  REPORT = 'Report',
  EXHIBITS = 'Exhibits',
  REVIEW = 'Review',
  SALES_COMPS_MAP = 'Sales Comps Map',
  LEASE_COMPS_MAP = 'Lease Comps Map',
  COST_COMPS_MAP = 'Cost Comps Map',
  COST_APPROACH = 'Cost Approach',
  COST_IMPROVEMENT = 'Cost Improvement',
  SALES_APPROACH_WEIGHT = 'Sales Approach Weight',
  COST_APPROACH_WEIGHT = 'Cost Approach Weight',
}

export enum SellerBuyierEnum {
  MARK_COMP_PRIVATE = 'Mark this comp private',
  NAME = 'Name',
  PERSON = 'person',
  COMPANY = 'company',
  ADD_NEW_PERSON = 'Add New Person...',
  ADD_NEW_COMPANY = 'Add New Company...',
  ADD_NEW = 'Add New...',
  SELLER_TYPE = 'Seller Type',
  LANDLORD_TYPE = 'Landlord Type',
  BUYER_TYPE = 'Buyer Type',
  TENANT_TYPE = 'Tenant Type',
  PLZ_SELECT_TYPE_FIRST = 'Please Select Type First',
  OFFEROR_TYPE = 'offeror_type',
  ACQUIRE_TYPE = 'acquirer_type',
  OFFEROR_ID = 'offeror_id',
  ACQUIRE_ID = 'acquirer_id',
  SELECT_PERSON = '--Select Person--',
  SELECT_COMPANY = '--Select Company--',
  PRIVATE_COMP = 'private_comp',
  SELECT = 'select',
  UPDATE = 'update',
  CREATE = 'create',
  PLZ_COMPLETE_MISSING_FIELD = 'Please complete the missing fields',
}

export enum FilterListingEnum {
  SEARCH_TYPE = 'SEARCH TYPE',
  SEARCH = 'SEARCH',
  LOCATION = 'LOCATION',
  ADVANCE_FILTER = 'ADVANCED FILTER',
  SORT_BY = 'Sort by',
  SALE_DATE_END = 'Sale Date End',
  APPLY = 'APPLY',
  MAP_SEARCH_FILTER = 'MapSearchFilter',
  DESC = 'DESC',
  ASC = 'asc',
  CITY = 'city',
  ADDITIONAL_CRITERIA = 'ADDITIONAL CRITERIA',
  SALE_DATE_START = 'Sale Date Start',
  DATE_SOLD = 'date_sold',
  LINK_SELECTED_COMPS = 'Link Selected Comps',
  ADJUST_SEARCH = 'Adjust Search',
  CLOSE = 'Close',
}

export enum MenuOptionsEnum {
  ANDROID = 'android',
  SEARCH_LISTINGS = 'Search Comps',
  PROPERTY_TYPE = 'Property Type',
  LIST_RESI = 'list-resi',
  LAND_ONLY = 'land_only',
  BUILDING_WITH_LAND = 'building_with_land',
  PER_NA = ' / NA',
}

export enum SortingEnum {
  Date_SOLD = 'date_sold',
  BUSINESS_NAME = 'business_name',
  STREET_ADDRESS = 'street_address',
  LEASE_RATE = 'lease_rate',
  PROPERTY_TYPE = 'property_name',
  LAND_SIZE_SF = 'land_size_sf',
  LAND_SIZE_ACRE = 'land_size_acre',
  CITY_STATE = 'city_state',

  YEAR_BUILT_YEAR_REMODELED = 'year_built_year_remodeled',
  YEAR_BUILT_REMODELED = 'year_built_remodeled',
  BUILDING_SIZE = 'building_size',
  BACKSPACE = 'Backspace',
  SIDEWALL_HEIGHT = 'sidewall_height',
  OFFICE_AREA = 'office_area',
  SALE_PRICE = 'sale_price',
  PRICE_PER_SF = 'price_per_sf',
  QUALITY_CONDITION = 'quality_condition',
  UNIT = 'unit',
  UNIT_ = 'Unit',
  PER_UNIT = ' / Unit',
  DOLLAR_PER_ACRE = '$/Acre',
  PER_ACRE = ' / Acre',
  PER_SF = ' / SF',
  PER_SF_ = '/ SF',
  HIGHEST_BEST_USE = 'highest_best_use',
  EFFECTIVE_AGE = 'effective_age',
  CAP_RATE = 'cap_rate',
  UNIT_MIX = 'unit_mix',
  PRICE_PER_UNIT = 'price_per_unit',
  TOPOGRAPHY = 'topography',
  UTILITIES_SELECT = 'utilities_select',
  ZONING_TYPE = 'zoning_type',
  CITY_COUNTY = 'city_county',
  BASEMENT_SF = 'basement_sf',
  GROSS_LIVING_AREA = 'gross_living_area',
  OTHER_AMENITIES = 'other_amenities',
  BASEMENT_DETAILS = 'Basement Details',

  ASC = 'asc',
  ASC_0 = 'asc_0',
  ASC_1 = 'asc_1',
  DESC = 'desc',
  DESC_0 = 'DESC_0',
  DESC_1 = 'DESC_1',
}

export enum SiteDetailsEnum {
  LAND_SIZE_SITE = 'land_size',
  LAND_DIMENSION = 'land_dimension',
  OTHER_TOPOGRAPHY = 'other_topography',
  LOT_SHAPE = 'lot_shape',
  FRONTAGE_SITE = 'frontage',
  FRONTAGE_CUSTOM = 'frontage_custom',
  SITE_ACCESS = 'site_access',
  UTILITIES_SELECT = 'utilities_select',
  OTHER_UTILITY = 'other_utility',
  SITE_COMMENTS = 'site_comments',
  TOPOGRAPHY_CUSTOM = 'topography_custom',
  TOPOGRAPHY = 'topography',
  UTILITIES_SELECT_CUSTOM = 'utilities_select_custom',
  LOT_SHAPE_CUSTOM = 'lot_shape_custom',
  OTHER_INCLUDED_UTILITIES = 'other_include_utilities',
  LAND_TYPE = 'land_type',
  LAND_TYPE_CUSTOM = 'land_type_custom',
  ENTER_CUSTOM_LAND_TYPE = 'Enter custom land type',
  SETUP = 'Setup',
}

export enum DeleteModalLabelEnum {
  DELETE_EXHIBIT = 'Delete Exhibit',
  DELETE_LIST = 'Delete List',
}

export enum ValidationStatusEnum {
  SUCCESS = 'success',
  ERROR = 'error',
  PENDING = 'pending',
  PENDING_ = 'Pending',
  VALIDATING = 'Validating',

  CLOSED = 'Closed',
  CUSTOM_VALIDATION_FAILED = 'Custom validation failed',
}

export enum UploadStatusEnum {
  ALREADY_EXIST = 'already exist',
  INVALID_ADDRESS = 'invalid address',
  ADDRESS_VALIDATION_FAILED = 'Address validation failed',
  MISSING_REQUIRED_FIELDS = 'Missing Required Fields',
  VALIDATING = 'Validating...',
  UPLOAD_AS_NEW = 'Upload as new',
  COMP_ALREADY_EXISTS = 'Comp already exists',
  VALIDATION_FAILED = 'Validation failed',
  PENDING = 'Pending',
  SKIPPED = 'Skipped',
  COMPLETED = 'Completed',
}

export enum LocalStorageKeysEnum {
  COMPS_LENGTH_SALES_EVALUATION = 'compsLengthsalesevaluation',
  COMPS_LENGTH_COST_EVALUATION = 'compsLengthcostevaluation',
  COMPS_LENGTH_LEASE_EVALUATION = 'compsLengthleaseevaluation',
  COMPS_LENGTH_CAP_EVALUATION = 'compsLengthcapevaluation',
  COMPS_LENGTH_MULTIFAMILY_EVALUATION = 'compsLengthmultifamilyevaluation',
  COMPS_LENGTH_SALES_APPRAISAL = 'compsLengthsalesappraisal',
  COMPS_LENGTH_COST_APPRAISAL = 'compsLengthcostappraisal',
  COMPS_LENGTH_LEASE_APPRAISAL = 'compsLengthleaseappraisal',
  PRESERVED_ACTIVE_TYPE = 'preservedActiveType',
  COMPARISON_BASIS_VIEW = 'comparisonBasisView',
  ACTIVE_TYPE = 'activeType',
  SELECTED_TOGGLE = 'selectedToggle',
  CHECK_STATUS = 'checkStatus',
  SALES = 'sales',
  COMPARISON_BASIS = 'comparisonBasis',
  APPRAISAL_TYPE = 'appraisalType',
  COMPS_LENGTH_LEASE = 'compsLengthLease',
  LEASE_APPROACH_VALUES_APPRAISAL = 'leaseApproachValuesAppraisal',
  SALES_APPROACH_VALUE_APPRAISAL = 'salesApproachValuesAppraisal',
  SALES_APPROACH_VALUES_RESIDENTIAL = 'salesApproachValuesResidential',
  VIEW = 'view',
}

export enum LocalStorageEnum {
  COMPS_LENGTH = 'compsLenght',
  CHECK_TYPE = 'checkType',
  LEASES_CHECKBOX = 'leasesCheckbox',
  LEASE_CHECKBOX = 'leaseCheckBox',
  APPROACH_TYPE = 'approachType',
  SELECTED_COST_ID = 'selectedCostId',
  COST_ID = 'costId',
  LEASE_CHECK = 'leaseCheck',
  SALES_APPROACH = '/sales-approach',
  SALES_CHECK = 'salesCheck',
  COST_APPROACH = '/cost-approach',
  APPROACH_ID = 'approachId',
  SEARCH_TERM = 'search_term',

  BUILDING_SF_MIN = 'building_sf_min',
  BUILDING_SF_MAX = 'building_sf_max',

  LAND_SF_MIN = 'land_sf_min',
  LAND_SF_MAX = 'land_sf_max',

  CAP_RATE_MIN = 'cap_rate_min',
  CAP_RATE_MAX = 'cap_rate_max',

  PRICE_SF_MIN = 'price_sf_min',
  PRICE_SF_MAX = 'price_sf_max',

  SQUARE_FOOTAGE_MIN = 'square_footage_min',
  SQUARE_FOOTAGE_MAX = 'square_footage_max',

  START_DATE = 'start_date',
  END_DATE = 'end_date',

  STATE = 'state',
  STREET_ADDRESS = 'street_address',

  COMP_STATUS = 'compStatus',

  PROPERTY_TYPE = 'property_type',
  LEASE_TYPE = 'lease_type',

  SELECTED_CITIES = 'selectedCities',
  SELECTED_SIZE = 'selectedSize',
}

export enum ToastMessagesEnum {
  MAX_SELECTION_WITH_EXISTING = 'are already linked. You can only link up to',
  MAX_SELECTION_EXCEEDED = 'You can only select up to',
  MORE_SUFFIX = 'more.',
  COMPS_SUFFIX = 'comps.',
  FILL_REQUIRED_FIELDS = '⚠️ Please fill in all required fields.',
  SELECT_ACTION_DROPDOWN = 'Please select an option from the action dropdown for all required rows.',
  SOME_COMPS_FAILED = 'Some comps failed to save. Please check the status column for details.',
  NETWORK_ERROR = 'Network error. Please check your connection and try again.',
  FAILED_TO_SAVE = 'Failed to save comps. Please try again.',
  INVALID_DATA = 'Invalid data provided. Please check your inputs and try again.',
}

export enum ActionStatesEnum {
  SKIP = 'Skip',
  UPLOAD_AS_NEW = 'Upload as New',
  UPDATE_EXISTING = 'Update Existing',
  UPLOAD_ANYWAY = 'Upload Anyway',
  RETRY = 'Retry',
}

export enum FieldNamesEnum {
  SELECTED = 'selected',
  STATE = 'state',
  LAND_DIMENSION = 'land_dimension',
  STREET_ADDRESS = 'street_address',
  CITY = 'city',
  DATE_SOLD = 'date_sold',
  BUILDING_TYPE = 'building_type',
  CONDITION = 'condition',
  BUILDING_SUB_TYPE = 'building_sub_type',
  LAND_TYPE = 'land_type',
  COMPARISON_BASIS = 'comparison_basis',
  LEASE_TYPE = 'lease_type',
  OFFEROR_TYPE = 'offeror_type',
  ACQUIRER_TYPE = 'acquirer_type',
  LEASE_STATUS = 'lease_status',
  SALE_STATUS = 'sale_status',
  UTILITIES_SELECT = 'utilities_select',
  LOT_SHAPE = 'lot_shape',
  PRIVATE_COMP = 'private_comp',
  TI_ALLOWANCE_UNIT = 'TI_allowance_unit',
  EXTERIOR = 'exterior',
  ROOF = 'roof',
  ELECTRICAL = 'electrical',
  PLUMBING = 'plumbing',
  HEATING_COOLING = 'heating_and_cooling',
  WINDOWS = 'windows',
  GARAGE = 'garage',
  TOPOGRAPHY = 'topography',
  FENCING = 'fencing',
  FIREPLACE = 'fireplace',
  BEDROOMS = 'bedrooms',
  BATHROOMS = 'bathrooms',
  ASKING_RENT_UNIT = 'asking_rent_unit',
  LEASE_RATE_UNIT = 'lease_rate_unit',
  BASEMENT = 'basement',
  PARKING = 'parking',
  FRONTAGE = 'frontage',
  FRONTAGE_CUSTOM = 'frontage_custom',
  BASEMENT_CUSTOM = 'basement_custom',
  ACTION = 'action',
  ENTER_CUSTOM_FRONTAGE = 'Enter custom frontage',
}

export enum ValidationFieldsEnum {
  STREET_ADDRESS = 'street_address',
  CITY = 'city',
  STATE = 'state',
  DATE_SOLD = 'date_sold',
}

export enum CustomFieldValuesEnum {
  TYPE_MY_OWN = 'Type My Own',
  TYPE_MY_OWN_LOWER = 'type_my_own',
}

export enum ErrorMessagesEnum {
  THIS_FIELD_REQUIRED = 'This field is required',
  ERROR_OCCURRED = 'Error occurred',
  FAILED_TO_SAVE = 'Failed to save',
}

export enum StatusDisplayEnum {
  PENDING = 'Pending',
  COMP_ALREADY_EXISTS_DISPLAY = 'Comp already exists',
  MISSING_REQUIRED_FIELDS_DISPLAY = 'Missing Required Fields',
  ADDRESS_VALIDATION_FAILED_DISPLAY = 'Address validation failed',
  UPLOAD_AS_NEW_DISPLAY = 'Upload as new',
}

export enum UILabelsEnum {
  LINK_COMP = 'Link Comp',
  ATTRIBUTE = 'Attribute',
  UPLOAD_STATUS = 'Upload Status',
  ACTION = 'Action',
  SELECT_ACTION = 'Select Action',
  COMP = 'Comp',
  SAVE = 'Save',
  LOADING = 'Loading...',
  VALIDATING_DATA = 'Validating data...',
  SAVING_COMPS = 'Saving comps...',
  RESIDENTIAL = 'residential',
  ACTIVE_MAIN = 'activeMain',
  ACTIVE_BUTTON = 'activeButton',
  RESIDENTIAL_DISPLAY = 'Residential',
  ENTER_STREET_ADDRESS = 'Enter street address',
  PENDING = 'Pending',
}

export enum APIEndpointsEnum {
  RES_COMPS_VALIDATE = 'resComps/validate-comp',
  RES_COMPS_SAVE = 'resComps/save-extracted-comp',
}

export enum PayloadFieldsEnum {
  COMP_TYPE = 'comp_type',
  TYPE = 'type',
  LEASE = 'lease',
  LEASE_ = 'Lease',
  SALE = 'sale',
  AI_GENERATED = 'ai_generated',
  NEW = 'new',
  UPDATE = 'update',
  UPLOAD_ANYWAY = 'uploadAnyway',
  TYPE_USE = 'Type/Use',
  RENT_ROLL = 'rent_roll',
}

export enum UnitsEnum {
  SF = 'SF',
  ACRE = 'ACRE',
  AC = 'AC',
}

export enum NumberFormatsEnum {
  DECIMAL_SUFFIX = '.000',
}

export enum CustomFieldsEnum {
  CONDITION = 'condition_custom',
  BUILDING_SUB_TYPE = 'building_sub_type_custom',
  PARKING = 'parking_custom',
  UTILITIES_SELECT = 'utilities_select_custom',
  TOPOGRAPHY = 'topography_custom',
  TOPOGRAPHY_SELECT = 'topography_select_custom',
  LAND_TYPE = 'land_type_custom',
  FRONTAGE = 'frontage_custom',
  ELECTRICAL = 'electrical_custom',
  EXTERIOR = 'exterior_custom',
  ROOF = 'roof_custom',
  GARAGE = 'garage_custom',
  HEATING_COOLING = 'heating_cooling_custom',
  PLUMBING = 'plumbing_custom',
  WINDOWS = 'windows_custom',
  FENCING = 'fencing_custom',
  FIREPLACE = 'fireplace_custom',
}

export enum RoutePathsEnum {
  EVALUATION_UPLOAD_SALES_COMPS = '/evaluation/upload-sales-comps',
  EVALUATION_UPLOAD_COST_COMPS = '/evaluation/upload-cost-comps',
  EVALUATION_UPLOAD_LEASE_COMPS = '/evaluation/upload-lease-comps',
  EVALUATION_UPLOAD_CAP_COMPS = '/evaluation/upload-cap-comps',
  EVALUATION_UPLOAD_MULTI_FAMILY_COMPS = '/evaluation/upload-multi-family-comps',
  APPRAISAL_UPLOAD_SALES_COMPS = '/appraisal/upload-sales-comps',
  APPRAISAL_UPLOAD_COST_COMPS = '/appraisal/upload-cost-comps',
  APPRAISAL_UPLOAD_LEASE_COMPS = '/appraisal/upload-lease-comps',
  RESIDENTIAL_EVALUATION_UPLOAD_SALES_COMPS = '/residential/evaluation/upload-sales-comps',
  RESIDENTIAL_UPLOAD_COMPS_SALES = '/residential/upload-comps-sales',
  RESIDENTIAL_EVALUATION_UPLOAD_COST_COMPS = '/residential/evaluation/upload-cost-comps',
  RESIDENTIAL_UPLOAD_COMPS_COST = '/residential/upload-comps-cost',
  RESIDENTIAL_SALES_APPROACH = '/residential/sales-approach',
  RESIDENTIAL_EVALUATION_COST_APPROACH = '/residential/evaluation/cost-approach',
}

export enum NavigationPathsEnum {
  RESIDENTIAL_EVALUATION_UPLOAD_SALES_COMPS = '/residential/evaluation/upload-sales-comps',
  RESIDENTIAL_UPLOAD_COMPS_SALES = '/residential/upload-comps-sales',
  RESIDENTIAL_EVALUATION_UPLOAD_COST_COMPS = '/residential/evaluation/upload-cost-comps',
  RESIDENTIAL_UPLOAD_COMPS_COST = '/residential/upload-comps-cost',
  RESIDENTIAL_SALES_APPROACH = '/residential/sales-approach',
  RESIDENTIAL_EVALUATION_COST_APPROACH = '/residential/evaluation/cost-approach',
}

export enum CustomFieldMappingsEnum {
  CONDITION_CUSTOM = 'condition',
  BUILDING_SUB_TYPE_CUSTOM = 'building_sub_type',
  PARKING_CUSTOM = 'parking',
  UTILITIES_SELECT_CUSTOM = 'utilities_select',
  TOPOGRAPHY_CUSTOM = 'topography',
  TOPOGRAPHY_SELECT_CUSTOM = 'topography_select',
  LAND_TYPE_CUSTOM = 'land_type',
  FRONTAGE_CUSTOM = 'frontage',
  ELECTRICAL_CUSTOM = 'electrical',
  EXTERIOR_CUSTOM = 'exterior',
  ROOF_CUSTOM = 'roof',
  GARAGE_CUSTOM = 'garage',
  HEATING_COOLING_CUSTOM = 'heating_cooling',
  PLUMBING_CUSTOM = 'plumbing',
  WINDOWS_CUSTOM = 'windows',
  FENCING_CUSTOM = 'fencing',
  FIREPLACE_CUSTOM = 'fireplace',
  BASEMENT_CUSTOM = 'basement',
  LOT_SHAPE_CUSTOM = 'lot_shape',
  ENTER_CUSTOM_TOPOGRAPHY = 'Enter custom topography',
}

export enum ColumnHeaderLabelsEnum {
  SUMMARY = 'Property Summary',
  NET_OPERATING_INCOME = 'Net Operating Income (NOI)',
  NET_OPERATING_INCOME_ = 'Net Operating Income',
  UTILITIES_SELECT = 'Utilities',
  UTILITIES_SELECT_CUSTOM = 'Other Utilities',
  TOPOGRAPHY = 'Topography',
  TOPOGRAPHY_CUSTOM = 'Other Topography',
  SPACE = 'Space(SF)',
  EST_LAND_VALUE = 'Estimated Land Value',
  LOCATION_DESC = 'Location Description',
  ASKING_RENT_UNIT = 'Asking Rent Units',
  TI_ALLOWANCE_UNIT = 'TI Allowance Units',
  DATE_LIST = 'List Date',
  DATE_EXPIRATION = 'Expiration Date',
  DATE_COMMENCEMENT = 'Commencement Date',
  DATE_EXECUTION = 'Execution Date',
  EST_BUILDING_VALUE = 'Building Residual',
  FREE_RENT = 'Free Rent(Months)',
  TERM = 'Term(Months)',
  CAM = 'CAM',
  STREET_SUITE = 'Suite Number',
  BASEMENT_FINISHED_SQ_FT = 'Basement Finished (SF)',
  BASEMENT_UNFINISHED_SQ_FT = 'Basement Unfinished (SF)',
  GROSS_LIVING_SQ_FT = 'Gross Living Area (SF)',
  WEIGHT_SF = 'SF Weighting',
  CAP_RATE = 'CAP Rate',
  LEGAL_DESC = 'Legal Description',
  OPERATING_EXPENSE_PSF = 'Operating Expense (PSF)',
  BASEMENT_FINISHED = 'basement finished',
  BASEMENT_UNFINISHED = 'basement unfinished',
  BASEMENT_FINISHED_ = 'Basement Finished',
  BASEMENT_UNFINISHED_ = 'Basement Unfinished',
  BASEMENT__FINISHED = 'basement_finished',
  BASEMENT__UNFINISHED = 'basement_unfinished',
  CALCULATE = 'Calculate',
}
