import { ResEvaluationsEnum } from '../utils/enums/ResEvaluationsEnum';
import { currentDateTime } from '../utils/common/Time';
import DefaultEnum from '../utils/enums/DefaultEnum';

const res_evaluations = (sequelize, DataTypes, model) => {
	const res_evaluations = sequelize.define(
		'res_evaluations',
		{
			id: {
				type: DataTypes.INTEGER(11),
				autoIncrement: true,
				primaryKey: true,
				allowNull: false,
			},
			property_id: DataTypes.INTEGER(11),
			user_id: DataTypes.INTEGER(11),
			account_id: DataTypes.INTEGER(11),
			client_id: DataTypes.INTEGER(11),
			property_name: DataTypes.STRING(255),
			street_address: DataTypes.STRING(255),
			street_suite: DataTypes.STRING(255),
			city: DataTypes.STRING(255),
			county: DataTypes.STRING(255),
			state: DataTypes.STRING(255),
			zipcode: DataTypes.INTEGER(11),
			type: DataTypes.STRING(255),
			under_contract_price: DataTypes.DECIMAL(10, 2),
			close_date: DataTypes.DATEONLY,
			last_transferred_date: DataTypes.DATEONLY,
			price: DataTypes.DECIMAL(10, 2),
			land_assessment: DataTypes.DECIMAL(10, 2),
			structure_assessment: DataTypes.DECIMAL(10, 2),
			sids: DataTypes.TEXT,
			taxes_in_arrears: DataTypes.DECIMAL(10, 2),
			tax_liability: DataTypes.DECIMAL(10, 2),
			property_image_url: DataTypes.TEXT,
			condition: DataTypes.STRING(255),
			property_class: DataTypes.STRING(255),
			year_built: DataTypes.STRING(255),
			year_remodeled: DataTypes.STRING(255),
			sale_price: DataTypes.FLOAT,
			price_square_foot: DataTypes.DOUBLE,
			building_size: DataTypes.DOUBLE,
			land_size: DataTypes.DOUBLE,
			land_dimension: DataTypes.TEXT,
			date_sold: DataTypes.DATEONLY,
			no_stories: DataTypes.STRING(255),
			parcel_id_apn: DataTypes.STRING(255),
			has_suite_parcel: DataTypes.TINYINT(1),
			has_cost_approach: DataTypes.TINYINT(1),
			has_income_approach: DataTypes.TINYINT(1),
			has_sales_approach: DataTypes.TINYINT(1),
			owner_of_record: DataTypes.TEXT,
			property_geocode: DataTypes.TEXT,
			property_legal: DataTypes.TEXT,
			property_rights: DataTypes.TEXT,
			high_and_best_user: DataTypes.TEXT,
			intended_use: DataTypes.TEXT,
			intended_user: DataTypes.TEXT,
			topography: DataTypes.STRING(255),
			frontage: DataTypes.STRING(255),
			front_feet: DataTypes.DOUBLE,
			lot_depth: DataTypes.DOUBLE,
			utilities_select: DataTypes.STRING(255),
			zoning_type: DataTypes.STRING(255),
			zoning_description: DataTypes.TEXT,
			services: DataTypes.STRING(255),
			height: DataTypes.STRING(255),
			main_structure_base: DataTypes.TEXT,
			foundation: DataTypes.TEXT,
			parking: DataTypes.TEXT,
			basement: DataTypes.TEXT,
			ada_compliance: DataTypes.STRING(255),
			date_of_analysis: DataTypes.DATEONLY,
			inspector_name: DataTypes.TEXT,
			report_date: DataTypes.DATEONLY,
			effective_date: DataTypes.DATEONLY,
			exterior: DataTypes.TEXT,
			roof: DataTypes.TEXT,
			electrical: DataTypes.TEXT,
			plumbing: DataTypes.TEXT,
			heating_cooling: DataTypes.TEXT,
			windows: DataTypes.TEXT,
			bedrooms: DataTypes.TEXT,
			bathrooms: DataTypes.TEXT,
			garage: DataTypes.TEXT,
			fencing: DataTypes.TEXT,
			fireplace: DataTypes.TEXT,
			additional_amenities: DataTypes.TEXT,
			other_amenities: DataTypes.TEXT,
			conforming_use_determination: DataTypes.TEXT,
			key_highlights: DataTypes.TEXT,
			site_details_north: DataTypes.TEXT,
			site_details_south: DataTypes.TEXT,
			site_details_east: DataTypes.TEXT,
			site_details_west: DataTypes.TEXT,
			traffic_street_address: DataTypes.TEXT,
			traffic_counts: DataTypes.TEXT,
			traffic_count: DataTypes.TEXT,
			traffic_input: DataTypes.DOUBLE,
			map_image_url: DataTypes.TEXT,
			map_zoom: DataTypes.INTEGER(11),
			map_selected_area: DataTypes.TEXT,
			map_pin_lat: DataTypes.TEXT,
			map_pin_lng: DataTypes.TEXT,
			map_pin_zoom: DataTypes.INTEGER(11),
			map_image_for_report_url: DataTypes.TEXT,
			google_place_id: DataTypes.TEXT,
			map_pin_image_url: DataTypes.INTEGER(11),
			latitude: DataTypes.STRING(255),
			longitude: DataTypes.STRING(255),
			exhibits: DataTypes.TEXT,
			county_details_url: DataTypes.TEXT,
			county_tax_url: DataTypes.TEXT,
			subdivision_survey_url: DataTypes.TEXT,
			weighted_market_value: DataTypes.DECIMAL(10, 2),
			position: DataTypes.TEXT,
			file_pdf_url: DataTypes.TEXT,
			submitted: {
				type: DataTypes.TINYINT(4),
				defaultValue: 0,
			},
			file_number: DataTypes.STRING(255),
			summary: DataTypes.TEXT,
			data: DataTypes.TEXT,
			rounding: DataTypes.INTEGER(11),
			last_updated: {
				type: DataTypes.DATE,
				defaultValue: sequelize.literal('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
			},
			created: DataTypes.DATE,
			last_transfer_date_known: {
				type: DataTypes.STRING(255),
				defaultValue: DefaultEnum.YES,
			},
			most_likely_owner_user: DataTypes.TEXT,
			review_summary: DataTypes.TEXT,
			comp_adjustment_mode: {
				type: DataTypes.STRING(255),
				defaultValue: DefaultEnum.PERCENT,
			},
			comp_type: {
				type: DataTypes.STRING(255),
				defaultValue: ResEvaluationsEnum.BUILDING_WITH_LAND,
			},
			lot_shape: DataTypes.STRING(255),
			aerial_map_zoom: DataTypes.INTEGER(11),
			comp_area_map_zoom: DataTypes.INTEGER(11),
			aerial_map_type: {
				type: DataTypes.STRING(50),
				defaultValue: DefaultEnum.ROAD_MAP,
			},
			comps_map_type: {
				type: DataTypes.STRING(50),
				defaultValue: DefaultEnum.ROAD_MAP,
			},
			assessed_market_year: DataTypes.STRING(255),
			tax_liability_year: DataTypes.STRING(255),
			total_land_improvement: DataTypes.DECIMAL(10, 2),
			linked_evals: DataTypes.TEXT,
			cost_comps_area_map_zoom: DataTypes.INTEGER(11),
			cost_comps_map_type: {
				type: DataTypes.STRING(50),
				defaultValue: DefaultEnum.ROAD_MAP,
			},
			weight_sf: DataTypes.INTEGER(11),
			evaluation_type: {
				type: DataTypes.STRING(30),
			},
			photos_taken_by: {
				type: DataTypes.STRING(255),
			},
			photo_date: {
				type: DataTypes.STRING(50),
			},
			map_center_lat: {
				type: DataTypes.STRING(30),
			},
			map_center_lng: {
				type: DataTypes.STRING(30),
			},
			reviewed_by: {
				type: DataTypes.INTEGER(11),
			},
			review_date: {
				type: DataTypes.DATEONLY,
			},
		},
		{
			timestamps: false, // Disable createdAt and updatedAt
			hooks: {
				beforeCreate: (instance) => {
					instance.last_updated = currentDateTime();
				},
			},
		},
	);
	res_evaluations.hasMany(model.res_zoning, {
		foreignKey: 'res_evaluation_id',
		sourceKey: 'id',
	});
	res_evaluations.hasMany(model.res_evaluation_scenarios, {
		foreignKey: 'res_evaluation_id',
		sourceKey: 'id',
	});
	return res_evaluations;
};

export default res_evaluations;
