import Joi from 'joi';
import CompsEnum from '../../utils/enums/CompsEnum';
import { dateFormatValidator } from '../../utils/common/helper';

export const mapBoundsSchema = Joi.object({
	bounds: Joi.object({
		north: Joi.number().required(),
		south: Joi.number().required(),
		east: Joi.number().required(),
		west: Joi.number().required(),
	}).required(),
	zoom: Joi.number().min(1).max(20).required(),
	center: Joi.object({
		lat: Joi.number(),
		lng: Joi.number(),
	}).optional(),
	filters: Joi.object({
		type: Joi.valid(CompsEnum.SALE, CompsEnum.LEASE).optional(),
		state: Joi.string().optional().allow(null, ''),
		city: Joi.array().optional().allow(null),
		propertyType: Joi.alternatives()
			.try(Joi.string(), Joi.array().items(Joi.string()))
			.optional()
			.allow(null, ''),
		start_date: dateFormatValidator.date().optional().allow(null, ''),
		end_date: dateFormatValidator.date().optional().allow(null, ''),
		building_sf_min: Joi.number().optional().allow(null),
		building_sf_max: Joi.number().optional().allow(null),
		land_sf_min: Joi.number().optional().allow(null),
		land_sf_max: Joi.number().optional().allow(null),
		cap_rate_min: Joi.number().optional().allow(null),
		cap_rate_max: Joi.number().optional().allow(null),
		page: Joi.number().optional().allow(null),
		limit: Joi.number().optional().allow(null),
		search: Joi.string().optional().allow(null, ''),
		orderBy: Joi.string().optional().allow(null, ''),
		orderByColumn: Joi.string().optional().allow(null, ''),
		street_address: Joi.string().optional().allow(null, ''),
		comparison_basis: Joi.string().optional().allow(null, ''),
		appraisal_land_dimension: Joi.string().optional().allow(null, ''),
		price_sf_max: Joi.number().optional().allow(null),
		price_sf_min: Joi.number().optional().allow(null),
		lease_type: Joi.string().optional().allow(null, ''),
		square_footage_max: Joi.number().optional().allow(null),
		square_footage_min: Joi.number().optional().allow(null),
		compStatus: Joi.string().optional().allow(null, ''),
		comp_type: Joi.string().optional().allow(null, ''),
		land_dimension: Joi.string().optional().allow(null, ''),
	}).optional(),
	limit: Joi.number().min(1).max(100).default(20).optional(),
	page: Joi.number().min(1).default(1).optional(),
});

export const clusterDetailsSchema = Joi.object({
	bounds: Joi.object({
		north: Joi.number().required(),
		south: Joi.number().required(),
		east: Joi.number().required(),
		west: Joi.number().required(),
	}).required(),
	zoom: Joi.number().min(1).max(20).required(),
	filters: Joi.object({
		type: Joi.string().optional(),
		propertyType: Joi.array().items(Joi.string()).optional(),
		priceMin: Joi.number().min(0).optional(),
		priceMax: Joi.number().min(0).optional(),
		sizeMin: Joi.number().min(0).optional(),
		sizeMax: Joi.number().min(0).optional(),
		yearBuiltMin: Joi.number().min(1800).max(new Date().getFullYear()).optional(),
		yearBuiltMax: Joi.number().min(1800).max(new Date().getFullYear()).optional(),
		dateFromMin: Joi.string().isoDate().optional(),
		dateFromMax: Joi.string().isoDate().optional(),
		capRateMin: Joi.number().min(0).max(100).optional(),
		capRateMax: Joi.number().min(0).max(100).optional(),
		leaseRateMin: Joi.number().min(0).optional(),
		leaseRateMax: Joi.number().min(0).optional(),
		termMin: Joi.number().min(0).optional(),
		termMax: Joi.number().min(0).optional(),
		condition: Joi.array().items(Joi.string()).optional(),
		zipcode: Joi.array().items(Joi.string()).optional(),
		city: Joi.array().items(Joi.string()).optional(),
		state: Joi.array().items(Joi.string()).optional(),
		search: Joi.string().max(255).optional(),
		land_dimension: Joi.string().optional().allow(null, ''),
	}).optional(),
	limit: Joi.number().min(1).max(100).default(20).optional(),
	page: Joi.number().min(1).default(1).optional(),
});

export const mapStatsSchema = Joi.object({
	bounds: Joi.object({
		north: Joi.number().required(),
		south: Joi.number().required(),
		east: Joi.number().required(),
		west: Joi.number().required(),
	}).required(),
	filters: Joi.object({
		type: Joi.string().optional(),
		propertyType: Joi.array().items(Joi.string()).optional(),
		priceMin: Joi.number().min(0).optional(),
		priceMax: Joi.number().min(0).optional(),
		sizeMin: Joi.number().min(0).optional(),
		sizeMax: Joi.number().min(0).optional(),
		yearBuiltMin: Joi.number().min(1800).max(new Date().getFullYear()).optional(),
		yearBuiltMax: Joi.number().min(1800).max(new Date().getFullYear()).optional(),
		dateFromMin: Joi.string().isoDate().optional(),
		dateFromMax: Joi.string().isoDate().optional(),
		capRateMin: Joi.number().min(0).max(100).optional(),
		capRateMax: Joi.number().min(0).max(100).optional(),
		leaseRateMin: Joi.number().min(0).optional(),
		leaseRateMax: Joi.number().min(0).optional(),
		termMin: Joi.number().min(0).optional(),
		termMax: Joi.number().min(0).optional(),
		condition: Joi.array().items(Joi.string()).optional(),
		zipcode: Joi.array().items(Joi.string()).optional(),
		city: Joi.array().items(Joi.string()).optional(),
		state: Joi.array().items(Joi.string()).optional(),
		search: Joi.string().max(255).optional(),
		land_dimension: Joi.string().optional().allow(null, ''),
	}).optional(),
});
