import { Typography } from '@mui/material';
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline';
import IncomeApprochSidebar from './income-sidebar';
import AppraisalMenu from '../set-up/appraisa-menu';
import { useState } from 'react';

const CreatIncomeApproch = () => {
  const [matchedApproch, setMatchedApproch] = useState('');
  const matchName = (event: any) => {
    setMatchedApproch(event);
  };
  return (
    <>
      <AppraisalMenu>
        <div>
          <div className="flex items-center justify-between h-[50px] w-[100%] xl:pl-[40px] border-0 border-b border-[#eee] border-solid xl:pr-[70px] px-[15px] map-header-sticky">
            <Typography
              variant="h1"
              component="h2"
              className="text-xl font-bold uppercase"
            >
              INCOME APPROACH ({matchedApproch})
            </Typography>
            <div className="flex items-center">
              <ErrorOutlineIcon className="pr-[10px] w-[30px] h-[30px]" />
              <span className="text-xs">
                Enter information about the income and expenses generated by the
                property.
              </span>
            </div>
          </div>
        </div>
        {/* <div> */}
        <div className="p-5 xl:px-14 px-4 ">
          <IncomeApprochSidebar matchName={matchName} />
        </div>
        {/* </div> */}
      </AppraisalMenu>
    </>
  );
};
export default CreatIncomeApproch;
