export enum AppraisalListingEnum {
  SELECT_TYPE = 'Select Type',
  STATE = 'State',
  STREET_ADDRESS = 'Street Address',
  DATE_ANALYSIS_FROM = 'dateOfAnalysisFrom',
  DATE_ANALYSIS_TO = 'dateOfAnalysisTo',
  RESET = 'Reset',
  SALE_DATE_END = 'Sale Date End',
  SALE_DATE_START = 'Sale Date Start',
  LOCATION = 'LOCATION',
  ADDITIONAL_CRITERIA = 'ADDITIONAL CRITERIA',
  SEARCH_TYPE = 'SEARCH TYPE',
  ADVANCED_FILTER = '  ADVANCED FILTER',
  APPRAISAL_LISTING = 'APPRAISAL LIST',
}

export enum IncomeApproachEnum {
  LAND_ONLY = 'land_only',
  UNIT = 'Unit',
  BED = 'Bed',
  SF_LAND = ' sf',
  SF = 'SF',
  TOTAL_NET_INCOME = 'total_net_income',
  TOTAL_OE_ANNUAL_AMOUNT = 'total_oe_annual_amount',
  PERCENTAGE_OF_GROSS = 'percentage_of_gross',
  TOTAL_PER_SQ_FT = 'total_per_sq_ft',
  ANNUAL_AMOUNT = 'annual_amount',
  TOTAL_OE_GROSS = 'total_oe_gross',
  TOTAL_OE_PER_SQ_FT = 'total_oe_per_square_feet',
  TOTAL_ANNUAL_INCOME = 'total_annual_income',
  OTHER_TOTAL_ANNUAL_INCOME = 'other_total_annual_income',
  TOTAL_MONTHLY_INCOME = 'total_monthly_income',
  TOTAL_RENT_SQ_FT = 'total_rent_sq_ft',
  ADJUST_GROSS_AMOUNT = 'adjusted_gross_amount',
  TOTAL_UNIT = 'total_unit',
  TOTAL_BED = 'total_bed',
  ANNUAL_INCOME = 'annual_income',
  MONTHLY_INCOME = 'monthly_income',
  RENT_SQ_FT = 'rent_sq_ft',
  TOTAL_OE_PER_UNIT = 'total_oe_per_unit',
  TOTAL_OE_PER_BED = 'total_oe_per_bed',
  TOTAL_ADJUSTED_COST = 'improvements_total_adjusted_cost',
  TOTAL_ADJUSTED_PPSF = 'improvements_total_adjusted_ppsf',
}
