export const columnHeaders = {
  business_name: 'Business Name',
  street_address: 'Street Address',
  street_suite: 'Street Suite',
  city: 'City',
  county: 'County',
  comparison_basis: 'Comparison Basis',
  state: 'State',
  zipcode: 'Zip Code',
  type: 'Type',
  property_image_url: 'Property Image URL',
  condition: 'Condition',
  condition_custom: 'Custom Condition',
  property_class: 'Property Class',
  year_built: 'Year Built',
  year_remodeled: 'Year Remodeled',
  sale_price: 'Sale Price',
  price_square_foot: 'Price per Square Foot',
  lease_rate: 'Lease Rate',
  term: 'Term',
  concessions: 'Concessions',
  building_size: 'Building Size',
  land_size: 'Land Size',
  summary: 'Summary',
  parcel_id_apn: 'Parcel ID/APN',
  frontage: 'Frontage',
  frontage_custom: 'Custom Frontage',
  utilities_select: 'Utilities',
  utilities_select_custom: 'Custom Utilities',
  zoning_type: 'Zoning Type',
  net_operating_income: 'Net Operating Income',
  map_pin_lat: 'Map Latitude',
  map_pin_lng: 'Map Longitude',
  map_pin_zoom: 'Map Zoom Level',
  latitude: 'Latitude',
  longitude: 'Longitude',
  cap_rate: 'Cap Rate',
  comp_type: 'Comparison Type',
  lease_type: 'Lease Type',
  topography: 'Topography',
  topography_custom: 'Custom Topography',
  lot_shape: 'Lot Shape',
  lot_shape_custom: 'Custom Lot Shape',
  lease_rate_unit: 'Lease Rate Unit',
  space: 'Space',
  cam: 'CAM',
  date_execution: 'Execution Date',
  date_commencement: 'Commencement Date',
  date_expiration: 'Expiration Date',
  TI_allowance: 'TI Allowance',
  TI_allowance_unit: 'TI Allowance Unit',
  asking_rent: 'Asking Rent',
  asking_rent_unit: 'Asking Rent Unit',
  escalators: 'Escalators',
  free_rent: 'Free Rent',
  lease_status: 'Lease Status',
  total_operating_expense: 'Total Operating Expense',
  operating_expense_psf: 'Operating Expense per SF',
  list_price: 'List Price',
  date_list: 'Listing Date',
  days_on_market: 'Days on Market',
  total_concessions: 'Total Concessions',
  offeror_type: 'Offeror Type',
  offeror_id: 'Offeror ID',
  acquirer_type: 'Acquirer Type',
  acquirer_id: 'Acquirer ID',
  private_comp: 'Private Comp',
  sale_status: 'Sale Status',
  land_dimension: 'Land Dimension',
  date_sold: 'Date Sold',
  occupancy: 'Occupancy',
  location_desc: 'Location Description',
  legal_desc: 'Legal Description',
  electrical: 'Electrical',
  electrical_custom: 'Electrical Custom',

  grantor: 'Grantor',
  grantee: 'Grantee',
  instrument: 'Instrument',
  confirmed_by: 'Confirmed By',
  confirmed_with: 'Confirmed With',
  financing: 'Financing',
  marketing_time: 'Marketing Time',
  est_land_value: 'Estimated Land Value',
  est_building_value: 'Estimated Building Value',
  construction_class: 'Construction Class',
  stories: 'Stories',
  site_access: 'Site Access',
  gross_building_area: 'Gross Building Area',
  net_building_area: 'Net Building Area',
  site_coverage_percent: 'Site Coverage (%)',
  effective_age: 'Effective Age',
  site_comments: 'Site Comments',
  building_comments: 'Building Comments',
  parking: 'Parking',
  parking_custom: 'Custom Parking',
  other_include_utilities: 'Other Included Utilities',
  included_utilities: 'Included Utilities',
  land_type: 'Land Type',
  land_type_custom: 'Custom Land Type',
  zonings: 'Zonings',
  property_units: 'Property Units',

  zone: 'Zone',
  sub_zone: 'Sub-Zone',
  sq_ft: 'Square Feet',
  unit: 'Unit',
  bed: 'Beds',
  sub_zone_custom: 'Custom Sub-Zone',

  // Property unit fields
  avg_monthly_rent: 'Average Monthly Rent',
  baths: 'Baths',
  beds: 'Beds',
  unit_count: 'Unit Count',
  exterior: 'Exterior',
  exterior_custom: 'Exterior Custom',
  roof: 'Roof',
  roof_custom: 'Roof_custom',
  plumbing: 'Plumbing',
  plumbing_custom: 'Plumbing Custom',
  heating_cooling: 'Heating/Cooling',
  heating_cooling_custom: 'Heating/Cooling Custom',

  windows: 'Windows',
  windows_custom: 'Windows Custom',
  bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms',
  garage: 'Garage',
  garage_custom: 'Garage Custom',
  fencing: 'Fencing',
  fencing_custom: 'fencing Custom',
  fireplace: 'Fireplace',
  other_amenities: 'Other menities',
};
export const landTypeOptions = {
  ag: 'Agricultural',
  cbd: 'Central Business District (CBD)',
  industrial: 'Industrial',
  residential_2_10_units: 'Residential - 2-10 Units',
  residential_multi_family: 'Residential - Multi-Family',
  residential_single_family: 'Residential - Single Family',
  retail_office: 'Retail/Office',
  subdivisions: 'Subdivisions',
  residential_development: 'Residential - Development',
};
export const landTypeOptionsComps = [
  { value: 'ag', label: 'Agricultural' },
  { value: 'cbd', label: 'Central Business District (CBD)' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'residential_2_10_units', label: 'Residential - 2-10 Units' },
  { value: 'residential_multi_family', label: 'Residential - Multi-Family' },
  { value: 'residential_single_family', label: 'Residential - Single Family' },
  { value: 'retail_office', label: 'Retail/Office' },
  { value: 'subdivisions', label: 'Subdivisions' },
  { value: 'residential_development', label: 'Residential - Development' },
  { value: 'Type My Own', label: 'Type My Own' },
];
