enum UserEnum {
	USER_NOT_FOUND = 'User not found',
	WRONG_PASSWORD = 'Wrong Password',
	LOGIN_SUCCESSFULLY = 'Logged in Successfully',
	USER_SAVE_SUCCESS = 'User Saved Successfully',
	ACCOUNT_DISABLED = 'Your account is disabled',
	INVALID_TOKEN = 'Token is invalid or expired',
	USER_INFO = 'User information',
	PASSWORD_NOT_UPDATE = 'There was a problem updating your password',
	PASSWORD_UPDATE = 'Your password has been updated. You may now login',
	TOKEN_REFRESHED = 'Your token has been refresh',
	PERMISSION_DENIED = 'Permission denied',
	USER_SAVE_FAIL = 'User Save Fail',
	INVALID_LOGIN = 'Login is invalid',
	NOT_APPROVED_BY_ADMIN = 'Your user has not been approved by an administrator yet',
	INVALID_ROLE = 'Invalid role',
	INVALID_ACCOUNT_ID = 'Invalid account id',
	ROLE_UPDATED_TO_ADMIN = 'Account details updated and The user role was updated to Account Administrator.',
	TOKEN_EXPIRED = 'Token is expired',
	INTERNAL_ERROR = 'Internal server error',
	UNAUTHORIZED = 'Unauthorized access',
}
export enum MailEnum {
	MAIL_SEND = 'Check your inbox for a password reset email',
	FORGOT_PASSWORD_SUBJECT = 'Forgot password | Harken CRE',
	EMAIL_ALREADY_TAKEN = 'This email already taken',
	EMAIL_UPDATED_SUCCESSFULLY = 'User email updated successfully',
	EMAIL_NOT_TAKEN = 'Email not taken',
	SETTING_PASSWORD = 'Set your password | Harken CRE',
	ACCOUNT_MANAGER_CREATED = 'Account details updated and The account manager was created and instructions were sent to the defined email.',
	SEND_INVITE_SUBJECT = 'Invitation | Harken Bankable Data',
	SEND_INVITE = 'The invitations were sent!',
}
export enum CompEnum {
	COMP_NOT_FOUND = 'Comp not found',
	COMP_SAVE_SUCCESS = 'Comp Saved Successfully',
	COMP_SAVE_FAIL = 'Comp Save fail',
	COMP_DATA = 'Comp Data',
	COMP_DELETED = 'Comp Delete Successfully',
	COMP_DELETE_FAIL = 'Comp Delete fail',
	COMP_EXIST_IN_EVAL_OR_APPRAISAL = 'This comp is currently used in an Evaluation or Appraisal and cannot be deleted.',
	STATE_NOT_SELECTED = 'Please select state',
	CITIES_NOT_FOUND = 'Cities not found',
	ALL_CITIES = 'All cities list',
	PERMISSION_DENIED = 'Permission denied',
	SELECT_COMP_ID = 'Comp id not selected',
	TEXT_EXTRACTION_FAILED = 'Failed to extract text from PDF.',
	COMPS_EXTRACTED_SUCCESS = 'Comps data extracted successfully',
}
export enum CompanyEnum {
	COMPANY_SAVE_SUCCESS = 'Company Saved Successfully',
	COMPANY_SAVE_FAIL = 'Company Save fail',
	COMPANY_ALREADY_EXIST = 'Company name already exists',
	COMPANY_LIST = 'Companies list',
	COMPANY_NOT_FOUND = 'Companies not found',
	NOT_FOUND = 'Company not found',
	COMPANY_DATA = 'Company data',
}
export enum ClientEnum {
	CLIENT_SAVE_SUCCESS = 'Client Saved Successfully',
	CLIENT_SAVE_FAIL = 'Client Save fail',
	CLIENTS_LIST = 'Clients list',
	CLIENTS_NOT_FOUND = 'Clients not found',
	CLIENT_UPDATE_FAIL = 'Clients not update',
	PERMISSION_DENIED = 'Do not have permission for this user',
	CLIENT_DELETE = 'Client deleted successfully',
	DELETE_CLIENT_FAIL = 'Client not deleted ',
	CLIENT_DATA = 'Client data',
	NOT_FOUND = 'Client not found',
}
export enum AccountsEnum {
	ACCOUNTS_DATA_NOT_FOUND = 'Accounts not found',
	ACCOUNTS_DATA = 'Accounts Data',
	ACCOUNT_SAVED = 'Accounts saved successfully',
	ACCOUNT_DELETED = 'Accounts deleted successfully',
	ACCOUNT_DELETE_FAIL = 'Account delete failed',
	ALREADY_DELETED_OR_NOT_FOUND = 'This account is already deleted or not found',
	ACCOUNT_UPDATE_FAILED = 'Failed to update account',
}

export enum TransactionEnum {
	TRANSACTION_NOT_FOUND = 'Transaction not found',
}

export enum FileEnum {
	FILE_UPLOAD_SUCCESS = 'File uploaded Successfully',
	FILE_UPLOAD_FAIL = 'File upload fail',
	FILE_DELETE_SUCCESS = 'File deleted Successfully',
	FILE_DELETE_FAIL = 'File delete fail',
}

export enum AppraisalEnum {
	APPRAISAL_NOT_FOUND = 'Appraisal not found',
	APPRAISALS_DATA_NOT_FOUND = 'Appraisals data not found',
	APPRAISAL_SAVE_SUCCESS = 'Appraisal Saved Successfully',
	APPRAISAL_SAVE_FAIL = 'Appraisal Save fail',
	APPRAISAL_DATA = 'Appraisal Data',
	APPRAISAL_DELETED = 'Appraisal Deleted Successfully',
	APPRAISAL_DELETE_FAIL = 'Appraisal Delete fail',
	APPROACH_UPDATE_SUCCESS = 'Appraisal approaches updated successfully',
	APPRAISAL_UPDATE_FAIL = 'Appraisal Updated fail',
	APPRAISAL_IMAGES_NOT_FOUND = 'Appraisal images not found',
	EXHIBIT_UPDATE_FAIL = 'Exhibit position update failed',
	EXHIBIT_UPDATE_SUCCESS = 'Exhibit position updated successfully',
	INCOME_APPROACH_SAVE_FAILED = 'Appraisal income approach save failed',
	INCOME_APPROACH_SAVED_SUCCESS = 'Appraisal income approach saved successfully',
	RECORD_ALREADY_EXIST = 'Record already exists for this appraisal_approach_id',
	INCOME_APPROACH_UPDATE_FAILED = 'Appraisal income approach update failed',
	INCOME_APPROACH_NOT_FOUND = 'Appraisal income approach not found',
	INCOME_APPROACH_DATA = 'Appraisal income approach data',
	PLEASE_PROVIDE_APPRAISAL_ID = 'Please provide appraisalId',
	PLEASE_PROVIDE_APPRAISAL_INCOME_APPROACH_ID = 'Please provide appraisalIncomeApproachId',
	PLEASE_PROVIDE_APPRAISAL_APPROACH_ID = 'Please provide appraisalApproachId',
	AREA_INFO_NOT_FOUND = 'Area info not found for requested appraisal',
	AREA_INFO_DATA = 'Area info data',
	INVALID_APPROACH_TYPE = 'Appraisal approach type is not valid',
	SALE_APPROACH_SAVE_FAIL = 'Sale approach save fail',
	SALE_APPROACH_SAVED_SUCCESS = 'Appraisal sale approach saved successfully',
	SALE_APPROACH_DATA = 'Appraisal sale approach data',
	SALES_APPROACH_NOT_FOUND = 'Appraisal sales approach not found',
	SALES_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Appraisal sales approach subject adjustments update failed',
	SALE_APPROACH_DATA_UPDATE_FAILED = 'Appraisal sale approach update failed',
	SALES_APPROACH_COMPS_UPDATE_FAILED = 'Appraisal sales approach comps update failed',
	COST_APPROACH_SAVED_SUCCESS = 'Appraisal cost approach saved successfully',
	COST_APPROACH_SAVE_FAIL = 'Cost approach save fail',
	COST_APPROACH_NOT_FOUND = 'Appraisal cost approach not found',
	COST_APPROACH_DATA = 'Appraisal cost approach data',
	COST_APPROACH_DATA_UPDATE_FAILED = 'Appraisal cost approach update failed',
	COST_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Appraisal cost approach subject adjustments update failed',
	COST_APPROACH_COMPS_UPDATE_FAILED = 'Appraisal cost approach comps update failed',
	COST_IMPROVEMENTS_SAVE_FAILED = 'Appraisal cost approach improvements save failed',
	COST_IMPROVEMENTS_SAVE_SUCCESS = 'Appraisal cost approach improvements saved successfully',
	AREA_INFO_UPDATE_FAILED = ' Area map info update failed',
	AREA_INFO_UPDATE_SUCCESS = 'Area info updated successfully',
	THIS_APPROACH_NOT_FOUND = 'This approach not found',
	INVALID_APPRAISAL_ID = 'Invalid appraisal id',
	REPORT_PREVIEW_SUCCESS = 'Report preview success',
	REPORT_DOWNLOADED = 'Report downloaded successfully',
	CAN_NOT_CHANGE_VALUE = 'This value cannot be changed after comps have been linked to the appraisal',
	SALE_SUB_QUALITATIVE_ADJ_UPDATE_FAIL = 'Appraisal sales approach subject qualitative adjustments update failed',
	LEASE_APPROACH_SAVE_FAIL = 'Lease approach save fail',
	LEASE_APPROACH_SAVED_SUCCESS = 'Appraisal lease approach saved successfully',
	LEASE_APPROACH_NOT_FOUND = 'Appraisal lease approach not found',
	LEASE_APPROACH_DATA_UPDATE_FAILED = 'Appraisal lease approach update failed',
	LEASE_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Appraisal lease approach subject adjustments update failed',
	LEASE_APPROACH_COMPS_UPDATE_FAILED = 'Appraisal lease approach comps update failed',
	LEASE_APPROACH_DATA = 'Appraisal lease approach data',
	RENT_ROLL_SAVED_SUCCESS = 'Rent roll saved successfully',
	RENT_ROLL_UPDATE_FAIL = 'Rent roll update failed',
	RENT_ROLL_TYPE_ALREADY_EXISTS = 'Rent roll already exists for this approach id',
	RENT_ROLL_DATA = 'Appraisal rent roll data',
	RENT_ROLL_NOT_FOUND = 'Rent roll data not found',
}

export enum WikipediaEnum {
	DATA_NOT_FOUND = 'Data not found',
	DATA_FOUND = 'Data found Successfully',
}

export enum TemplateEnum {
	TEMPLATE_SAVE_SUCCESS = 'Saved successfully',
	TEMPLATE_SAVE_FAILED = 'Template save failed',
	TEMPLATE_UPDATE_FAILED = 'Template update failed',
	TEMPLATE_DELETE_SUCCESS = 'Template deleted successfully',
	TEMPLATE_DELETE_FAILED = 'Template delete failed',
	ENTER_VALID_TEMPLATE_ID = 'Please enter valid template id',
	TEMPLATE_NOT_FOUND = 'Template not found',
	TEMPLATE_LIST_SUCCESS = 'Template list success',
	DATA_NOT_FOUND = 'Data not found',
	MERGE_FIELDS_NOT_FOUND = 'Merge fields not found',
	SNIPPETS_NOT_FOUND = 'Snippets not found',
	SNIPPETS_CATEGORY_NOT_FOUND = 'Snippets category not found',
	ORDER_BY = 'field',
	TEMPLATE_ALREADY_EXISTS = 'Template already exists for this appraisal id',
	INVALID_TEMPLATE_ID = 'Template id is invalid',
}

export enum SectionEnum {
	ENTER_VALID_ID = 'Enter valid section id',
	SECTION_NOT_FOUND = 'Section not found',
	SECTION_DELETE_FAILED = 'Section delete failed',
	SECTION_DELETE_SUCCESS = 'Section delete success',
	SECTION_UPDATE_FAILED = 'Section update failed',
	SECTION_SAVE_SUCCESS = 'Section save success',
	SECTION_SAVE_FAILED = 'Section save failed',
	TYPE = 'type',
	MAP = 'map',
	AERIAL_MAP = 'aerial_map',
	SALE_APPROACH_COMPS_MAP = 'sale_approach_comps_map',
	COST_APPROACH_COMPS_MAP = 'cost_approach_comps_map',
	APPROACH = 'approach',
	ITEM_NOT_FOUND = 'Item not found',
	ITEM_DELETED_SUCCESSFULLY = 'Item deleted successfully',
	ITEM_DELETE_FAIL = 'Item delete fail',
	ITEM_SAVE_FAILED = 'Item save failed',
	ITEM_SAVE_SUCCESS = 'Item saved successfully',
	ITEM_UPDATE_FAIL = 'Item update failed',
	IMAGE = 'image',
	TEXT_BLOCK = 'text_block',
	SUBSECTION = 'subsection',
	PHOTO_PAGES = 'photo_pages',
	INCOME_COMPARISON = 'income_comparison',
}
export enum SnippetEnum {
	SNIPPET_SAVE_SUCCESS = 'Snippet saved successfully',
	SNIPPET_SAVE_FAILED = 'Snippet save failed',
	SNIPPET_UPDATE_FAILED = 'Snippet update failed',
	SNIPPET_NOT_FOUND = 'Snippet not found',
	SNIPPET_NAME_ALREADY_EXIST = 'Snippet with this name already exists',
	SNIPPET_DELETE_SUCCESS = 'Snippet deleted successfully',
	SNIPPET_DELETE_FAILED = 'Snippet delete failed',
	SNIPPET_CATEGORY_NAME_ALREADY_EXIST = 'Snippet category with this name already exists',
	SNIPPET_CATEGORY_SAVE_SUCCESS = 'Snippet category saved successfully',
	SNIPPET_CATEGORY_SAVE_FAILED = 'Snippet category save failed',
	SNIPPET_CATEGORY_UPDATE_FAILED = 'Snippet category update failed',
	SNIPPET_CATEGORY_NOT_FOUND = 'Snippet category not found',
	SNIPPET_CATEGORY_DELETE_SUCCESS = 'Snippet category deleted successfully',
}
export enum CommonEnum {
	STATES_NOT_FOUND = 'States not found',
	STATES_LIST = 'States list',
	GLOBAL_CODE_CATEGORY_NOT_FOUND = 'Global codes category not found',
	GLOBAL_CODE_CATEGORIES_LIST = 'Global codes categories list',
}
export enum PhotoPagesEnum {
	PHOTOS_SAVED_SUCCESSFULLY = 'Photos saved successfully',
	PHOTO_PAGES = 'Photo pages data',
}
export enum DownloadCompEnum {
	NOT_AVAILABLE = 'N/A',
	COMPS_NOT_SELECTED = 'Comps not selected to print',
	LEASE_TYPES = 'lease_types',
	LEASE_RATE_UNIT = 'lease_rate_unit',
	COMPANY = 'company',
	PERSON = 'person',
	LOT_SHAPE = 'lot_shape',
	LEASE_STATUS = 'lease_status',
	SF = ' SF',
	PERCENT = '%',
	TI_ALLOWANCE_UNIT = 'TI_allowance_unit',
}
export enum EvalMessageEnum {
	EVALUATION_NOT_FOUND = 'Evaluation not found',
	EVALUATION_UPDATE_FAIL = 'Evaluation update failed',
	EVALUATION_SAVE_SUCCESS = 'Evaluation saved successfully',
	EVALUATION_SAVE_FAIL = 'Evaluation save failed',
	EVALUATION_DELETE_SUCCESS = 'Evaluation deleted successfully',
	EVALUATION_DELETE_FAIL = 'Evaluation delete failed',
	EVALUATION_DATA = 'Evaluation data',
	EVALUATION_LIST = 'Evaluation list',
	EVALUATION_LIST_NOT_FOUND = 'Evaluation list not found',
	EVALUATION_LIST_DATA = 'Evaluation list data',
	EVALUATION_LIST_DATA_NOT_FOUND = 'Evaluation list data notfound',
	EVALUATION_ID = 'evaluation_id',
	INVALID_EVALUATION_ID = 'Invalid evaluation id',
	MAP_BOUNDARY_SAVE_SUCCESS = 'Map boundary saved successfully',
	MAP_BOUNDARY_SAVE_FAIL = 'Map boundary save failed',
	EVALUATION_IMAGES_NOT_FOUND = 'Evaluation images not found',
	EXHIBIT_UPDATE_FAIL = 'Exhibit update failed',
	EXHIBIT_UPDATE_SUCCESS = 'Exhibit updated successfully',
	INVALID_APPROACH_TYPE = 'Invalid approach type',
	RECORD_ALREADY_EXIST = 'Record already exists',
	INCOME_APPROACH_SAVE_FAILED = 'Income approach save failed',
	INCOME_APPROACH_SAVED_SUCCESS = 'Income approach saved successfully',
	INCOME_APPROACH_NOT_FOUND = 'Income approach not found',
	INCOME_APPROACH_UPDATE_FAILED = 'Income approach update failed',
	PLEASE_PROVIDE_EVALUATION_ID = 'Please provide evaluation id',
	PLEASE_PROVIDE_EVALUATION_SCENARIO_ID = 'Please provide evaluation scenario id',
	INCOME_APPROACH_DATA = 'Income approach data',
	AREA_INFO_DATA = 'Area info data',
	SALE_APPROACH_SAVE_FAIL = 'Sale approach save failed',
	SALE_APPROACH_SAVED_SUCCESS = 'Sale approach saved successfully',
	SALE_APPROACH_DATA_UPDATE_FAILED = 'Sale approach data update failed',
	SALES_APPROACH_NOT_FOUND = 'Sale approach not found',
	SALES_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Sale approach subject adjustment update failed',
	SALE_SUB_QUALITATIVE_ADJ_UPDATE_FAIL = 'Sale subject qualitative adjustment update failed',
	SALES_APPROACH_COMPS_UPDATE_FAILED = 'Sale approach comps update failed',
	SALE_APPROACH_DATA = 'Sale approach data',
	THIS_APPROACH_NOT_FOUND = 'This approach not found',
	AREA_INFO_UPDATE_FAILED = ' Area map info update failed',
	AREA_INFO_UPDATE_SUCCESS = 'Area info updated successfully',
	EVALUATION_DELETED = 'Evaluation Deleted Successfully',
	COST_APPROACH_SAVED_SUCCESS = 'Evaluation cost approach saved successfully',
	COST_APPROACH_SAVE_FAIL = 'Cost approach save failed',
	COST_APPROACH_NOT_FOUND = 'Evaluation cost approach not found',
	COST_APPROACH_DATA = 'Evaluation cost approach data',
	COST_APPROACH_DATA_UPDATE_FAILED = 'Evaluation cost approach update failed',
	COST_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Evaluation cost approach subject adjustments update failed',
	COST_APPROACH_COMPS_UPDATE_FAILED = 'Evaluation cost approach comps update failed',
	COST_IMPROVEMENTS_SAVE_FAILED = 'Evaluation cost approach improvements save failed',
	COST_IMPROVEMENTS_SAVE_SUCCESS = 'Evaluation cost approach improvements saved successfully',
	CAN_NOT_CHANGE_VALUE = 'This value cannot be changed after comps have been linked to the Evaluation',
	LEASE_APPROACH_SAVE_FAIL = 'Lease approach save failed',
	LEASE_APPROACH_SAVED_SUCCESS = 'Evaluation lease approach saved successfully',
	LEASE_APPROACH_NOT_FOUND = 'Evaluation lease approach not found',
	LEASE_APPROACH_DATA_UPDATE_FAILED = 'Evaluation lease approach update failed',
	LEASE_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Evaluation lease approach subject adjustments update failed',
	LEASE_APPROACH_COMPS_UPDATE_FAILED = 'Evaluation lease approach comps update failed',
	LEASE_APPROACH_DATA = 'Evaluation lease approach data',
	RENT_ROLL_SAVED_SUCCESS = 'Rent roll saved successfully',
	RENT_ROLL_UPDATE_FAIL = 'Rent roll update failed',
	RENT_ROLL_TYPE_ALREADY_EXISTS = 'Rent roll already exists for this scenario id.',
	RENT_ROLL_DATA = 'Evaluation rent roll data',
	RENT_ROLL_NOT_FOUND = 'Rent roll data not found',
	CAP_APPROACH_SAVE_FAIL = 'Cap approach save failed',
	CAP_APPROACH_SAVED_SUCCESS = 'Evaluation Cap approach saved successfully',
	CAP_APPROACH_NOT_FOUND = 'Evaluation Cap approach not found',
	CAP_APPROACH_DATA_UPDATE_FAILED = 'Evaluation cap approach update failed',
	CAP_APPROACH_COMPS_UPDATE_FAILED = 'Evaluation cap approach comps update failed',
	CAP_APPROACH_DATA = 'Cap approach data',
	MULTI_FAMILY_APPROACH_SAVE_FAIL = 'Multi-Family approach save failed',
	MULTI_FAMILY_APPROACH_SAVED_SUCCESS = 'Evaluation Multi-Family approach saved successfully',
	MULTI_FAMILY_APPROACH_NOT_FOUND = 'Evaluation Multi-Family approach not found',
	MULTI_FAMILY_APPROACH_DATA_UPDATE_FAILED = 'Evaluation Multi-Family approach update failed',
	MULTI_FAMILY_APPROACH_SUB_ADJ_UPDATE_FAILED = 'Evaluation Multi-Family approach subject adjustments update failed',
	MULTI_FAMILY_APPROACH_COMPS_UPDATE_FAILED = 'Evaluation Multi-Family approach comps update failed',
	MULTI_FAMILY_APPROACH_DATA = 'Evaluation Multi-Family approach data',
	COMPARISON_ATTRIBUTE_UPDATE_FAILED = 'Comparison attributes update failed',
	EVALUATION_APPROACH_UPDATE_FAILED = 'Evaluation approach update failed',
	REPORT_PREVIEW_SUCCESS = 'Report preview success',
	SCENARIO_NOT_FOUND = 'Scenario not found',
	APPROACH_NOT_SELECTED_IN_THIS = 'This Approach is not selected.',
	PLEASE_PROVIDE_MULTI_FAMILY_ID = 'Please provide evaluation multiFamily id',
}
export default UserEnum;
