export enum AmenitiesEnum {
  AMENITIES = 'AMENITIES',
  EXTERIOR = 'Exterior',
  EXTERIOR_NAME = 'exterior',
  TYPE_MY_OWN = 'Type My Own',
  ROOF = 'Roof',
  ROOF_NAME = 'roof',
  OTHER_ROOF = 'Other Roof',
  ROOF_CUSTOM = 'roof_custom',
  ELECTRICAL = 'Electrical',
  ELECTRICAL_NAME = 'electrical',
  OTHER_ELECTRICAL = 'Other Electrical',
  ELECTRICAL_CUSTOM = 'electrical_custom',
  PLUMBING = 'Plumbing',
  PLUMBING_NAME = 'plumbing',
  OTHER_PLUMBING = 'Other Plumbing',
  PLUMBING_CUSTOM = 'plumbing_custom',
  HEATING_COOLING = 'Heating/Cooling',
  HEATING_COOLING_NAME = 'heating_cooling',
  OTHER_HEATING_COOLING = 'Other Heating/Cooling',
  HEATING_COOLING_CUSTOM = 'heating_cooling_custom',
  WINDOWS = 'Windows',
  WINDOWS_NAME = 'windows',
  OTHER_WINDOWS = 'Other Windows',
  WINDOWS_CUSTOM = 'windows_custom',
  OTHER_EXTERIOR = 'Other Exterior',
  EXTERIOR_CUSTOM = 'exterior_custom',
}
export enum AnalysisEnum {
  ANALYSIS = ' ANALYSIS',
  DATE_OF_INSPECTION = 'Date of Inspection',
  DATE_OF_ANALYSIS = 'date_of_analysis',
  EFFECTIVE_DATE = 'Effective Date',
  EFFECTIVE_DATE_NAME = 'effective_date',
  INSPECTOR_NAME = 'Inspector Name',
  INSPECTOR_NAME_NAME = 'inspector_name',
  REPORT_DATE = 'Report Date',
  REPORT_DATE_NAME = 'report_date',
}

export enum BuildingWithLandEnum {
  ZONINGS = 'zonings',
  ZONE = 'zone',
  SUB_ZONE = 'sub_zone',
  OTHER_SUBZONE = 'Other Sub Property Type',
  SUB_ZONE_CUSTOM = 'sub_zone_custom',
  SQ_FT_NAME = 'sq_ft',
  SQ_FT = 'SQ.FT',
  WEIGHT_SF = 'weight_sf',
  SF_WEIGHTING = 'SF Weighting',
  NOTES = 'Notes : ',
  NOTES_PARAGARAPH = 'Weightings are only used for the Sales Comparison Approach when the Comparison Basis is SF.',
}
export enum MapBoundariesEnum {
  MAP_BOUNDARIES = 'MAP BOUNDARIES',
  TRAFFIC_COUNTS = 'Traffic Counts - ',
  TRAFFIC_COUNTS_PARAGARAPH = 'Numbers based on the average daily traffic (ADT)',
  INPUT_VALUE = 'inputvalue',
  TRAFFIC_COUNT_ADT = 'Traffic Count (ADT)',
  TRAFFIC_COUNT = 'traffic_count',
  TRAFFIC_COUNT_ADT_VALUE = 'Traffic Count (ADT) Value',
  TRAFFIC_INPUT = 'traffic_input',
  SAVE_AND_CONTINUE = ' SAVE & CONTINUE',
  TRAFFIC_STREET_ADDRESS = 'traffic_street_address',
  STREET_ADDRESS = 'Street Address',
}
export enum OverviewEnum {
  OVERVIEW = 'OVERVIEW',
  MULTI_FAMILY = 'multi_family',
}
export enum PropertyDetailsEnum {
  PROPERTY_DETAILS = ' PROPERTY DETAILS',
  REPORT_TITLE = 'Report Title',
  BUSINESS_NAME = 'business_name',
  LATITUDE = 'latitude',
  LONGITUDE = 'longitude',
  ZIPCODE = 'ZIP Code',
  SUITE_NUMBER = 'Suite Number',
  STREET_SUITE = 'street_suite',
  SELECT_STATE = '-Select State-',
  STATE = 'state',
  ZIPCODE_NAME = 'zipcode',
  COUNTRY = 'County',
  COUNTRY_NAME = 'country',
  TYPE = 'Type',
  TYPE_NAME = 'type',
  UNDER_CONTRACT_PRICE = 'Under Contract Price',
  UNDER_CONTRACT_PRICE_NAME = 'under_contract_price',
  CLOSE_DATE = 'Close Date',
  CLOSE_DATE_NAME = 'close_date',
  YES = 'YES',
  NO = 'NO',
  LAST_SALE_DATE = 'Last Sale Date',
  APN_PARCEL_ID_TAX_ID = 'APN / PARCEL ID / TAX ID',
  PARCEL_ID_APN = 'parcel_id_apn',
  OWNER_OF_RECORD = 'Owner of Record',
  OWNER_OF_RECORD_NAME = 'owner_of_record',
  PROPERTY_GEOCODE = 'Property Geocode',
  PROPERTY_GEOCODE_NAME = 'property_geocode',
  PROPERTY_LEGAL = 'Property Legal',
  PROPERTY_LEGAL_NAME = 'property_legal',
  PROPERTY_RIGHTS = 'Property Rights',
  PROPERTY_RIGHTS_NAME = 'property_rights',
  OTHER_PROPERTY_RIGHTS_TYPE = 'Other Property Rights Type',
  PROPERTY_RIGHTS_CUSTOM = 'property_rights_custom',
  LAST_TRANSFER_DATE = 'last_transferred_date',
  FILE = 'File #',
  FILE_NUMBER = 'file_number',
  PROPERTY_INTENDED_USE = 'Report Intended Use',
  INTENDED_USE = 'intended_use',
  INTENDED_USERS = 'Intended User(s)',
  INTENDED_USER = 'intended_user',
  CITY = 'City',
  CITY_NAME = 'city',
  IS_LAST_SALE_DATE = 'Is last sale date known?',
  LAST_TRANSFER_DATE_UNKNOWN = 'last_transfer_date_known',
  PRICE_LABEL = 'Price',
  PRICE = 'price',
  COUNTY = 'county',
}

export enum PropertyDetailsEnumParams {
  SALE = 'sale',
  NON_SALE = 'non_sale',
}

export enum SpecificationEnum {
  SPECIFICATIONS = ' SPECIFICATIONS',
  BUILDING_WITH_LAND = ' Building With Land',
  BUILDING_WITH_LAND_VALUE = 'building_with_land',
  LAND_ONLY_VALUE = 'land_only',
  LAND_ONLY = 'Land Only',
  COMPARISION_BASIS = 'Comparison Basis',
  COMPARISION_BASIS_NAME = 'comparison_basis',
  LOT_SIZE = 'Lot Size',
  LAND_SIZE = 'land_size',
  SIZE_TYPE = 'Size Type',
  LAND_DIMENSION = 'land_dimension',
  HIGHEST_AND_BEST_USE = 'Highest and Best Use',
  HIGH_AND_BEST_USER = 'high_and_best_user',
  MOST_LIKELY_OWNER_USER = 'Most likely Owner/User',
  MOST_LIKELY_OWNER_USER_NAME = 'most_likely_owner_user',
  OTHER_MOST_LIKELY_OWNER_USER = 'Other Most likely Owner/User',
  MOST_LIKELY_OWNER_USER_CUSTOM = 'most_likely_owner_user_custom',
  TOPOGRAPHY = 'Topography',
  TOPOGRAPHY_NAME = 'topography',
  OTHER_TOPOGRAPHY = 'Other Topography',
  TOPOGRAPHY_CUSTOM = 'topography_custom',
  LOT_SHAPE = 'Lot Shape',
  OTHER_LAND_TYPE = 'Other Land Type',
  LOT_SHAPE_NAME = 'lot_shape',
  OTHER_LOT_SHAPE = 'Other Lot Shape',
  LOT_SHAPE_CUSTOM = 'lot_shape_custom',
  LAND_TYPE_CUSTOM = 'land_type_custom',
  FRONTAGE = 'Frontage',
  FRONTAGE_NAME = 'frontage',
  OTHER_FRONTAGE = 'Other Frontage',
  FRONTAGE_CUSTOM = 'frontage_custom',
  LOT_FRONTAGE = 'Lot Frontage',
  FRONT_FEET = 'front_feet',
  LOT_DEPTH = 'Lot Depth',
  LOT_DEPTH_NAME = 'lot_depth',
  UTILITIES = 'Utilities',
  UTILITIES_SELECT = 'utilities_select',
  OTHER_UTILITIES = 'Other Utilities',
  UTILITIES_SELECT_CUSTOM = 'utilities_select_custom',
  PROPERTY_SUMMARY = 'Property Summary',
  SUMMARY = 'summary',
  PROPERTY_CONDITION = 'Property Condition',
  CONDITION = 'condition',
  OTHER_CONDITION_TYPE = 'Other Condition Type',
  CONDITION_CUSTOM = 'condition_custom',
  PROPERTY_CLASS = 'Property Class',
  PROPERTY_CLASS_NAME = 'property_class',
  OTHER_PROPERTY_CLASS_TYPE = 'Other Property Class Type',
  PROPERTY_CLASS_CUSTOM = 'property_class_custom',
  YEAR_BUILD = 'Year Built',
  YEAR_BUILT = 'year_built',
  BASE_YEAR_REMODELED = 'Base Year Remodeled',
  YEAR_REMODELED = 'year_remodeled',
  CEILING_HEIGHT = 'Ceiling Height',
  HEIGHT = 'height',
  STORIES = '# Stories',
  NO_STORIES = 'no_stories',
  FOUNDATION = 'Foundation',
  FOUNDATION_NAME = 'foundation',
  OTHER_FOUNDATION = 'Other Foundation',
  FOUNDATION_CUSTOM = 'foundation_custom',
  PARKING = 'Parking',
  PARKING_NAME = 'parking',
  OTHER_PARKING = 'Other Parking',
  PARKING_CUSTOM = 'parking_custom',
  BASEMENT = 'Basement',
  BASEMENT_NAME = 'basement',
  OTHER_BASEMENT = 'Other Basement',
  BASEMENT_CUSTOM = 'basement_custom',
  ADA_COMPLIANCE = 'ADA Compliance',
  ADA_COMPLIANCE_NAME = 'ada_compliance',
  OTHER_ADA_COMPLIANCE = 'Other ADA Compliance',
  ADA_COMPLIANCE_CUSTOM = 'ada_compliance_custom',
  STRUCTURE_CONSTRUCTION_TYPE = 'Structure Construction Type',
  MAIN_STRUCTURE_BASE = 'main_structure_base',
  OTHER_STRUCTURE_CONSTRUCTION_TYPE = 'Other Structure Construction Type',
  MAIN_STRUCTURE_BASE_CUSTOM = 'main_structure_base_custom',
  COMP_TYPE = 'comp_type',
  ANALYSIS_TYPE = 'Analysis Type',
  ANALYSIS_TYPE_NAME = 'analysis_type',
  LAND_TYPE = ' Land Type',
  LAND_TYPE_NAME = 'land_type',
  UNIT = 'Unit',
  COST = 'cost',
}

export enum TaxAssessmentEnum {
  TAX_ASSESSMENT = 'TAX ASSESSMENT',
  LAND_ASSESSMENT = 'Land Assessment',
  LAND_ASSESSMENT_NAME = 'land_assessment',
  IMPORVEMENT_ASSESSED_VALUE = 'Improvements Assessed Value',
  STRUCTURE_ASSESSMENT = 'structure_assessment',
  LAND_PLUS_IMROVEMENTS = 'Land + Improvements',
  TOTAL_LAND_IMPROVEMENT = 'total_land_improvement',
  $_SF = '$/SF',
  PRICE_SQUARE_FOOT = 'price_square_foot',
  SIDS = "SID'S",
  SIDS_NAME = 'sids',
  TAXES_IN_ARREARS = 'Taxes in Arrears',
  TAXES_IN_ARREARS_NAME = 'taxes_in_arrears',
  TAX_LIABILITY = 'Tax Liability',
  TAX_LIABILITY_NAME = 'tax_liability',
  ASSESSED_MARKET_VALUE_YEAR = 'Assessed market Value Year',
  ASSESSED_MARKET_YEAR = 'assessed_market_year',
  TAX_LIABILITY_YEAR = 'Tax Liability Year',
  TAX_LIABILITY_YEAR_NAME = 'tax_liability_year',
}
export enum ZoningsEnum {
  ZONING = 'ZONING',
  ZONING_TYPE = 'Zoning Type',
  ZONING_TYPE_NAME = 'zoning_type',
  ZONING_DESCRIPTION = 'Zoning Description (Only 2500 characters allowed)',
  ZONING_DESCRIPTION_NAME = 'zoning_description',
  CONFIRMING_USER_DETERMINATION = 'Conforming Use Determination',
  CONFIRMING_USER_DETERMINATION_NAME = 'conforming_use_determination',
}
export enum AppraisalPhotoPagesEnum {
  CLICK_HERE_TO_ADD_IMAGE = 'Click here to add image',
  UPLOAD = 'Upload',
  SAVE_AND_CONTINUE = 'SAVE AND CONTINUE',
  ADD_PROPERTY_IMAGE = 'Add Property Image',
  CAPTION = 'Caption',
  IMAGE = 'Image',
  ACTION = 'Action',
  PHOTOS = 'Photos',
  HEADER = 'Upload photos to be used in this Appraisal.',
  PHOTO_PAGE_HEADER = 'Upload photos to be used in this evaluation.',
  PHOTO_TAKEN_BY = 'Photo Taken By',
  PHOTO_DATE = 'Photo Date',
  REQUIRED = 'This field is required.',
}
export enum ImageOrientation {
  HORIZONTAL = 'Horizontal',
  VERTICAL = 'Vertical',
}

export enum PageType {
  COVER = '1 - Cover Photo',
  TABLE_OF_CONTENTS = '2 - Table of Contents',
  EXECUTIVE_SUMMARY = '5 - Executive Summary',
  PROPERTY_SUMMARY = '7 - Property Summary',
  PROPERTY_DETAILS = '16',
}

export enum UniqueValueKeys {
  COVER = 'cover',
  TABLE_OF_CONTENTS = 'table-of-contents',
  EXECUTIVE_SUMMARY = 'executive-summary-details',
  PROPERTY_SUMMARY_TOP = 'property-summary-top-image',
  PROPERTY_SUMMARY_BOTTOM = 'property-summary-bottom-image',
  SUB_PROPERTY_1 = 'sub-property-1',
  SUB_PROPERTY_2 = 'sub-property-2',
  SUB_PROPERTY_3 = 'sub-property-3',
  EXTRA_IMAGE = 'extraImage',
}

export enum ActionTypes {
  SAVE_SUCCESS = 'The image has been saved.',
  UPLOAD_ERROR = 'Error uploading image',
  SELECT_IMAGE = 'Please Select Image',
}

export enum ButtonLabels {
  UPLOAD = 'Upload',
  SAVE_CONTINUE = 'SAVE AND CONTINUE',
  ADD_PROPERTY_IMAGE = 'Add Property Image',
}

export enum TableHeaders {
  IMAGE = 'Image',
  DESCRIPTION = 'Description',
  ORIENTATION = 'Orientation',
  PAGE = 'Page',
  ACTION = 'Action',
}

export enum PropertyTypes {
  LAND_ONLY = 'land_only',
}

export enum AnalysisTypes {
  SF = '$/SF',
  ACRE = '$/Acre',
}

export enum LandDimension {
  SF = 'SF',
  ACRE = 'ACRE',
}
